import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import {describe, expect, it} from "vitest";

describe("Manager GUI shared Electron payload contract", () => {
    it("uses a separate GUI entry but the same Electron runtime and secure preload", async () => {
        const build = await readFile(resolve("desktop/electron/build.mjs"), "utf8");
        const main = await readFile(resolve("desktop/electron/src/main.ts"), "utf8");
        const manager = await readFile(resolve("desktop/electron/src/manager-main.ts"), "utf8");
        const uacClient = await readFile(resolve("packages/neuro-book-manager/src/desktop-uac-client.ts"), "utf8");
        const managerCli = await readFile(resolve("packages/neuro-book-manager/src/cli.ts"), "utf8");
        const desktopInstallation = await readFile(resolve("packages/neuro-book-manager/src/desktop-installation.ts"), "utf8");
        const preload = await readFile(resolve("desktop/electron/src/manager-preload.ts"), "utf8");
        const html = await readFile(resolve("desktop/electron/src/manager.html"), "utf8");
        const packager = await readFile(resolve("desktop/packaging/package-portable.mjs"), "utf8");

        expect(build).toContain('naming: "manager-main.mjs"');
        expect(build).toContain('naming: "manager-preload.cjs"');
        expect(main).toContain("--manager-gui");
        expect(manager).toContain("nodeIntegration: false");
        expect(manager).toContain("contextIsolation: true");
        expect(manager).toContain("event.sender !== window.webContents");
        expect(manager).toContain("event.senderFrame !== window.webContents.mainFrame");
        expect(manager).toContain('"manager:run"');
        expect(manager).toContain('window.once("closed", quitManager)');
        expect(manager).toContain('"manager:quit"');
        expect(manager).toContain("quitManager()");
        expect(preload).toContain("contextBridge.exposeInMainWorld");
        expect(preload).toContain('"manager:open-logs"');
        expect(manager).toContain("AUTH_ADMIN_PASSWORD: undefined");
        expect(manager).toContain("runDesktopUacClient");
        expect(manager).toContain("@notnotype/neuro-book-manager/desktop-uac-client");
        expect(manager).toContain('"desktop-repair"');
        expect(manager).toContain("waitForWindowsUninstallHostResult");
        expect(manager).toContain("Manager CLI uninstall 缺少最终回执");
        expect(manager).not.toContain("function launchElevatedBroker");
        expect(manager).not.toContain("Start-Process -FilePath");
        expect(uacClient).toContain("validateSecretPipeHello");
        expect(uacClient).toContain("windowsCommandLineQuote");
        expect(uacClient).toContain("UAC 未批准或提升进程未连接");
        const elevatedLaunchStart = uacClient.indexOf("function launchElevatedBroker");
        const elevatedLaunchEnd = uacClient.indexOf("function receiveElevatedEvents");
        expect(elevatedLaunchStart).toBeGreaterThanOrEqual(0);
        expect(elevatedLaunchEnd).toBeGreaterThan(elevatedLaunchStart);
        expect(uacClient.slice(elevatedLaunchStart, elevatedLaunchEnd)).not.toContain('"-NonInteractive"');
        expect(managerCli).toContain('desktop.command("broker-client")');
        expect(managerCli).toContain('action: "uninstall"');
        expect(managerCli).toContain('args: ["--root", installationRoot, "uninstall", "--yes", "--json"]');
        expect(managerCli).toContain("deleteData: false");
        expect(desktopInstallation).toContain('"broker-client"');
        expect(desktopInstallation).not.toContain("$elevatedCommand");
        expect(packager).toContain('join(envelopeDist, "manager-main.mjs")');
        expect(packager).toContain('join(envelopeDist, "manager-preload.cjs")');
        expect(packager).toContain("NeuroBook-Manager.cmd");
        expect(html).toContain("校验并安装");
        expect(html).toContain('id="adminPassword" type="password"');
        expect(html).toContain("id=\"enableAuth\"");
        expect(html).toContain('kind: "install"');
        expect(html).toContain('kind: "uninstall", deleteData');
        expect(html).toContain('id="deleteData" type="checkbox"');
        expect(html).toContain("托管的 State Root");
        expect(html).toContain("function clearSecrets()");
        expect(html).toContain('data-step="5"');
        expect(html).toContain("maxVisitedStep");
        expect(html).toContain('document.querySelectorAll("[data-step-target]")');
        expect(html).toContain('id="gitProvider"');
        expect(html).toContain('id="rgProvider"');
        expect(html).toContain('id="channel"');
        expect(html).toContain('id="localSourceKind"');
        expect(html).toContain('value="aggregate-depot"');
        expect(html).toContain('id="discoverModels"');
        expect(html).toContain("result.providerTest");
        expect(html).toContain("程序已安装，Provider 尚未保存");
        expect(html).toContain('retryMode = "provider"');
        expect(html).toContain(`Content-Security-Policy" content="default-src 'none'`);
        expect(html).toContain('id="apiKey" type="password"');
        expect(html).toContain('value="openai-responses"');
        expect(html).not.toContain('id="api" value="openai-completions"');
    });
    it("跨边界能力只通过 Manager 与 contracts 正式入口消费", async () => {
        const packager = await readFile(resolve("desktop/packaging/package-portable.mjs"), "utf8");
        const managerCli = await readFile(resolve("packages/neuro-book-manager/src/cli.ts"), "utf8");
        const appPackage = JSON.parse(await readFile(resolve("packages/neuro-book/package.json"), "utf8")) as {dependencies?: Record<string, string>; imports?: Record<string, string>};
        const managerPackage = JSON.parse(await readFile(resolve("packages/neuro-book-manager/package.json"), "utf8")) as {exports?: Record<string, unknown>};

        expect(managerCli).not.toContain("nbook/desktop/");
        expect(packager).not.toContain("../../shared/desktop-contract");
        expect(packager).not.toContain("../../shared/product-runtime");
        expect(packager).toContain("@notnotype/neuro-book-manager/product-runtime-verifier");
        expect(managerPackage.exports?.["./desktop-uac-client"]).toBeTruthy();
        expect(managerPackage.exports?.["./product-runtime-verifier"]).toBeTruthy();
        expect(JSON.stringify(appPackage.dependencies ?? {})).not.toContain("desktop");
        expect(JSON.stringify(appPackage.imports ?? {})).not.toContain("desktop/");
    });
});
