import type {PlotTreeGraph} from "nbook/app/components/novel-ide/plot/tree/plot-tree.types";

/**
 * PlotTree 独立测试页 mock 数据。
 * 重点覆盖：主线、fork、跨线程分叉、游离 Scene。
 */
export const plotTreePreviewGraph: PlotTreeGraph = {
    story: {
        id: "story-ash-harbor",
        title: "灰烬孤港",
        summary: "围绕买下奴隶少女后的控制权争夺、旧钥匙秘库和情感反咬，验证主线、支线、游离节点与连线编辑。",
        startLabel: "主线开始",
    },
    threads: [
        {
            id: "thread-main",
            title: "主线：买下奴隶少女",
            summary: "核心因果线，负责逆袭、控制权转换与身份升级。",
            status: "active",
            isMainThread: true,
            tone: "amber",
            position: {x: 260, y: 80},
        },
        {
            id: "thread-blackmail",
            title: "支线：账册勒索线",
            summary: "从笼边试探分叉出来的黑账支线，用于加速主角的议价资本。",
            status: "active",
            isMainThread: false,
            tone: "sky",
            position: {x: 260, y: 500},
        },
        {
            id: "thread-emotion",
            title: "支线：风暴夜情感反咬",
            summary: "从主线高压关系中分叉出的情感攻防线，强调拉扯与背刺感。",
            status: "draft",
            isMainThread: false,
            tone: "rose",
            position: {x: 260, y: 900},
        },
    ],
    scenes: [
        {
            id: "scene-auction",
            threadId: "thread-main",
            title: "拍卖台抬价",
            summary: "主角用超高价格压住全场，强行买下少女，故事从这里开始起势。",
            status: "written",
            chapterLabel: "Chapter 01",
            sourceId: "plot-root-start",
            isMainBranch: true,
            position: {x: 28, y: 96},
        },
        {
            id: "scene-cage",
            threadId: "thread-main",
            title: "笼边第一次对话",
            summary: "少女第一次反向定价自己，主线开始出现双向试探。",
            status: "active",
            chapterLabel: "Chapter 01",
            sourceId: "scene-auction",
            isMainBranch: true,
            position: {x: 280, y: 96},
        },
        {
            id: "scene-ledger",
            threadId: "thread-main",
            title: "账册房里的反咬",
            summary: "主角掌握亏空账册，第一次真正把控制权从买主手里撬开。",
            status: "active",
            chapterLabel: "Chapter 02",
            sourceId: "scene-cage",
            isMainBranch: true,
            position: {x: 532, y: 96},
        },
        {
            id: "scene-vault",
            threadId: "thread-main",
            title: "塔楼秘库开启",
            summary: "从账册房继续走主线，旧钥匙把目标从财富反转成身份真相。",
            status: "draft",
            chapterLabel: "Chapter 05",
            sourceId: "scene-ledger",
            isMainBranch: true,
            position: {x: 784, y: 96},
        },
        {
            id: "scene-escape",
            threadId: "thread-main",
            title: "以名字换自由",
            summary: "主线继续前推，主角通过秘库记录拿回改写身份的主动权。",
            status: "draft",
            chapterLabel: "Chapter 06",
            sourceId: "scene-vault",
            isMainBranch: true,
            position: {x: 1036, y: 96},
        },
        {
            id: "scene-blackmail",
            threadId: "thread-blackmail",
            title: "黑账的侧门入口",
            summary: "笼边试探后 fork 出来的支线，主角决定从账本切入另一条勒索路径。",
            status: "draft",
            chapterLabel: null,
            sourceId: "scene-cage",
            isMainBranch: false,
            position: {x: 28, y: 96},
        },
        {
            id: "scene-contract",
            threadId: "thread-blackmail",
            title: "债契被反写",
            summary: "支线继续推进，原本压人的债契反被主角用作锁喉工具。",
            status: "draft",
            chapterLabel: "Chapter 03",
            sourceId: "scene-blackmail",
            isMainBranch: false,
            position: {x: 280, y: 96},
        },
        {
            id: "scene-storm",
            threadId: "thread-emotion",
            title: "风暴夜半句坦白",
            summary: "账册房之后 fork 出来的情感支线，买主第一次露出真正的恐惧来源。",
            status: "draft",
            chapterLabel: "Chapter 04",
            sourceId: "scene-ledger",
            isMainBranch: false,
            position: {x: 28, y: 96},
        },
        {
            id: "scene-kiss-knife",
            threadId: "thread-emotion",
            title: "吻前藏刀",
            summary: "情感线继续推进，但推进方式仍然是互相利用与随时背刺。",
            status: "draft",
            chapterLabel: null,
            sourceId: "scene-storm",
            isMainBranch: false,
            position: {x: 280, y: 96},
        },
        {
            id: "scene-spy",
            threadId: null,
            title: "码头线人的匿名传信",
            summary: "游离 Scene，用于测试不归属任何 Thread 的临时灵感节点和后续归组操作。",
            status: "draft",
            chapterLabel: null,
            sourceId: null,
            isMainBranch: false,
            position: {x: 980, y: 620},
        },
    ],
};
