import {existsSync} from "node:fs";
import {mkdir, readFile, writeFile} from "node:fs/promises";
import {dirname, join} from "node:path";
import {PROFILE_COMPILED_DIR_NAME, readProfileArtifactManifest, type ProfileArtifactPathContext} from "nbook/server/agent/profiles/profile-artifact-compiler";
import {generateBuiltinVariableTypes, type VariableTypeGenerationDiagnostic} from "nbook/server/agent/variables/generated-types";
import {readVariableDefinitionManifest, VARIABLE_DEFINITION_COMPILED_DIR, type VariableDefinitionArtifactPathContext} from "nbook/server/agent/variables/definition-artifact";

export type GenerateProfileVariableIdeTypesOptions = {
    outputPath: string;
    variableDefinitionRoots: ReadonlyArray<{
        root: string;
        artifactPathContext: VariableDefinitionArtifactPathContext;
    }>;
    profileRoots: ReadonlyArray<{
        root: string;
        artifactPathContext: ProfileArtifactPathContext;
    }>;
};

/**
 * 生成给 IDE / tsconfig 稳定引用的变量类型入口。
 * Runtime 不读取该文件；它只是把当前已编译 artifact 的 authoring types 汇总到固定路径。
 */
export async function generateProfileVariableIdeTypes(options: GenerateProfileVariableIdeTypesOptions): Promise<{
    outputPath: string;
    includedFiles: string[];
    diagnostics: VariableTypeGenerationDiagnostic[];
}> {
    const includedFiles: string[] = [];
    const diagnostics: VariableTypeGenerationDiagnostic[] = [];
    const builtinTypes = generateBuiltinVariableTypes();
    const sections = [builtinTypes.text];
    diagnostics.push(...builtinTypes.diagnostics);
    for (const target of options.variableDefinitionRoots) {
        const manifest = await readVariableDefinitionManifest(target.root, target.artifactPathContext);
        for (const item of manifest.definitions) {
            if (!item.typeFileName) {
                continue;
            }
            const typePath = join(target.root, VARIABLE_DEFINITION_COMPILED_DIR, item.typeFileName);
            if (!existsSync(typePath)) {
                continue;
            }
            includedFiles.push(typePath);
            sections.push(await readFile(typePath, "utf8"));
            diagnostics.push(...item.typeDiagnostics ?? []);
        }
    }

    for (const target of options.profileRoots) {
        const manifest = await readProfileArtifactManifest(target.root, target.artifactPathContext);
        for (const item of manifest.profiles) {
            if (!item.typeFileName) {
                continue;
            }
            const typePath = join(target.root, PROFILE_COMPILED_DIR_NAME, item.typeFileName);
            if (!existsSync(typePath)) {
                continue;
            }
            includedFiles.push(typePath);
            sections.push(await readFile(typePath, "utf8"));
            diagnostics.push(...item.typeDiagnostics ?? []);
        }
    }

    const text = [
        "/* eslint-disable */",
        "// This file is generated by scripts/build/generate-profile-variable-types.ts.",
        "// It is a stable IDE entry for ProfileVariableAccessor authoring types.",
        "// Runtime variable truth stays in registry and compiled artifacts.",
        "",
        ...sections.map(stripGeneratedTypePreamble).filter(Boolean),
        "",
    ].join("\n");
    await mkdir(dirname(options.outputPath), {recursive: true});
    await writeFile(options.outputPath, text, "utf8");
    return {outputPath: options.outputPath, includedFiles, diagnostics};
}

function stripGeneratedTypePreamble(text: string): string {
    return text
        .split(/\r?\n/)
        .filter((line) => !line.startsWith("/* eslint-disable */")
            && !line.startsWith("// This file is generated.")
            && !line.startsWith("// ")
            && line.trim() !== "export {};")
        .join("\n")
        .trim();
}
