/**
 * 简单演示 API：返回服务端时间与提示信息。
 */

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Hello"
    ],
    "summary": "Server health check — returns message and server time",
    "responses": {
        "200": {
            "description": "OK"
        }
    }
} as never,
});

export default defineEventHandler(() => {
    return {
        message: "Hello from Nuxt server api",
        now: new Date().toISOString(),
    };
});
