import {z} from "zod";
import {ProjectRootDtoSchema} from "nbook/shared/dto/project.dto";
import {createWorkspaceDirectoryTracked, USER_LOCAL_ACTOR} from "nbook/server/workspace-history/tracked-workspace-files";
import {resolveWorkspaceFileTarget} from "nbook/server/workspace-files/novel-workspace";
import {withProjectTargetMutation} from "nbook/server/workspace-files/project-open-guard";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Workspace Files"
    ],
    "summary": "Create a new workspace directory",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "projectRoot": {
                            "description": "Project Workspace root, single directory name under Workspace Root",
                            "type": "string"
                        },
                        "workspaceKind": {
                            "description": "Use the global user assets workspace",
                            "type": "string",
                            "enum": [
                                "user-assets"
                            ]
                        },
                        "path": {
                            "type": "string",
                            "minLength": 1,
                            "description": "Directory path"
                        },
                        "indexContent": {
                            "description": "Index file content",
                            "nullable": true,
                            "type": "string"
                        }
                    },
                    "required": [
                        "path"
                    ],
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK"
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

const CreateWorkspaceDirectoryBodySchema = z.object({
    projectRoot: ProjectRootDtoSchema.optional(),
    workspaceKind: z.literal("user-assets").optional(),
    path: z.string().trim().min(1, "path 不能为空"),
    indexContent: z.string().nullable().optional(),
});

/**
 * 创建工作区目录。
 */
export default defineEventHandler(async (event) => {
    const body = CreateWorkspaceDirectoryBodySchema.parse(await readBody(event));
    const target = await resolveWorkspaceFileTarget(runtimePathsFromEnv(), body);
    return withProjectTargetMutation(target, async (projectHandles) => {
        const node = await createWorkspaceDirectoryTracked({
            target,
            history: projectHandles?.history,
            dirPath: body.path,
            indexContent: body.indexContent,
            actor: USER_LOCAL_ACTOR,
        });
        return node;
    });
});
