import {z} from "zod";
import {ProjectRootDtoSchema} from "nbook/shared/dto/project.dto";
import {deleteWorkspacePathTracked, USER_LOCAL_ACTOR} from "nbook/server/workspace-history/tracked-workspace-files";
import {resolveWorkspaceFileTarget} from "nbook/server/workspace-files/novel-workspace";
import {withProjectTargetMutation} from "nbook/server/workspace-files/project-open-guard";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Workspace Files"
    ],
    "summary": "Delete a workspace file or directory",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "projectRoot": {
                            "description": "Project Workspace root, single directory name under Workspace Root",
                            "type": "string"
                        },
                        "workspaceKind": {
                            "description": "Use the global user assets workspace",
                            "type": "string",
                            "enum": [
                                "user-assets"
                            ]
                        },
                        "path": {
                            "type": "string",
                            "minLength": 1,
                            "description": "Path to delete"
                        },
                        "recursive": {
                            "default": false,
                            "description": "Delete recursively",
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "path",
                        "recursive"
                    ],
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "success": {
                                "type": "boolean"
                            }
                        },
                        "required": [
                            "success"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

const DeleteWorkspacePathBodySchema = z.object({
    projectRoot: ProjectRootDtoSchema.optional(),
    workspaceKind: z.literal("user-assets").optional(),
    path: z.string().trim().min(1, "path 不能为空"),
    recursive: z.boolean().optional().default(false),
});

/**
 * 删除工作区文件或目录。
 */
export default defineEventHandler(async (event) => {
    const body = DeleteWorkspacePathBodySchema.parse(await readBody(event));
    const target = await resolveWorkspaceFileTarget(runtimePathsFromEnv(), body);
    return withProjectTargetMutation(target, async (projectHandles) => {
        await deleteWorkspacePathTracked({target, history: projectHandles?.history, filePath: body.path, recursive: body.recursive, actor: USER_LOCAL_ACTOR});
        return {success: true};
    });
});
