import {z} from "zod";
import {ProjectRootDtoSchema} from "nbook/shared/dto/project.dto";
import {renameWorkspacePathTracked, USER_LOCAL_ACTOR} from "nbook/server/workspace-history/tracked-workspace-files";
import {resolveWorkspaceFileTarget} from "nbook/server/workspace-files/novel-workspace";
import {withProjectTargetMutation} from "nbook/server/workspace-files/project-open-guard";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Workspace Files"
    ],
    "summary": "Rename or move a workspace path",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "projectRoot": {
                            "description": "Project Workspace root, single directory name under Workspace Root",
                            "type": "string"
                        },
                        "workspaceKind": {
                            "description": "Use the global user assets workspace",
                            "type": "string",
                            "enum": [
                                "user-assets"
                            ]
                        },
                        "from": {
                            "type": "string",
                            "minLength": 1,
                            "description": "Source path"
                        },
                        "to": {
                            "type": "string",
                            "minLength": 1,
                            "description": "Destination path"
                        }
                    },
                    "required": [
                        "from",
                        "to"
                    ],
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK"
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

const RenameWorkspacePathBodySchema = z.object({
    projectRoot: ProjectRootDtoSchema.optional(),
    workspaceKind: z.literal("user-assets").optional(),
    from: z.string().trim().min(1, "from 不能为空"),
    to: z.string().trim().min(1, "to 不能为空"),
});

/**
 * 移动或重命名工作区路径。
 */
export default defineEventHandler(async (event) => {
    const body = RenameWorkspacePathBodySchema.parse(await readBody(event));
    const target = await resolveWorkspaceFileTarget(runtimePathsFromEnv(), body);
    return withProjectTargetMutation(target, async (projectHandles) => {
        const node = await renameWorkspacePathTracked({target, history: projectHandles?.history, fromPath: body.from, toPath: body.to, actor: USER_LOCAL_ACTOR});
        return node;
    });
});
