import {
    assertFullTreeSnapshotQuery,
    readPlainWorkspaceTreeSnapshot,
    readProjectWorkspaceTreeSnapshot,
} from "nbook/server/workspace-files/project-workspace-index";
import {resolveWorkspaceFileTarget} from "nbook/server/workspace-files/novel-workspace";
import {withProjectTargetOperation} from "nbook/server/workspace-files/project-open-guard";
import {runtimePathsFromEnv} from "nbook/server/runtime/paths/runtime-paths";
import {createServerTiming} from "nbook/server/utils/server-timing";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Workspace Files"
    ],
    "summary": "Read workspace tree snapshot",
    "parameters": [
        {
            "name": "projectRoot",
            "in": "query",
            "required": false,
            "schema": {
                "description": "Project Workspace root, single directory name under Workspace Root",
                "type": "string"
            },
            "description": "Project Workspace root, single directory name under Workspace Root"
        },
        {
            "name": "workspaceKind",
            "in": "query",
            "required": false,
            "schema": {
                "description": "Use the global user assets workspace",
                "type": "string",
                "enum": [
                    "user-assets"
                ]
            },
            "description": "Use the global user assets workspace"
        }
    ],
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "nodes": {
                                "type": "array",
                                "items": {},
                                "description": "Workspace file nodes"
                            },
                            "issues": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "level": {
                                            "type": "string",
                                            "enum": [
                                                "P1",
                                                "P2",
                                                "P3",
                                                "WARN"
                                            ]
                                        },
                                        "code": {
                                            "type": "string"
                                        },
                                        "path": {
                                            "type": "string"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "line": {
                                            "type": "number"
                                        }
                                    },
                                    "required": [
                                        "level",
                                        "code",
                                        "path",
                                        "message"
                                    ],
                                    "additionalProperties": false
                                },
                                "description": "Project Workspace issues; empty for user-assets"
                            },
                            "revision": {
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 9007199254740991,
                                "description": "Project Workspace File Index revision"
                            },
                            "validatedAt": {
                                "type": "string",
                                "description": "ISO timestamp for the latest snapshot validation"
                            }
                        },
                        "required": [
                            "nodes",
                            "issues",
                            "revision",
                            "validatedAt"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        }
    }
} as never,
});






/**
 * 读取工作区文件树。
 */
export default defineEventHandler(async (event) => {
    const timing = createServerTiming(event);
    const query = getQuery(event);
    const projectRoot = typeof query.projectRoot === "string" ? query.projectRoot : undefined;
    const workspaceKind = query.workspaceKind === "user-assets" ? query.workspaceKind : undefined;
    const type = typeof query.type === "string" && query.type.trim() ? query.type.trim() : null;
    const depth = typeof query.depth === "string" ? Number.parseInt(query.depth, 10) : null;
    const targets = parseTargets(query.target);
    const parsedDepth = Number.isSafeInteger(depth) ? depth : null;
    assertFullTreeSnapshotQuery({
        targets,
        type,
        depth: parsedDepth,
    });

    const target = await timing.measure("workspace.resolve", () => (
        resolveWorkspaceFileTarget(runtimePathsFromEnv(), {projectRoot, workspaceKind})
    ));
    return withProjectTargetOperation(target, (projectHandles) => {
        if (target.kind !== "project-workspace") {
            return timing.measure("workspace.tree", () => readPlainWorkspaceTreeSnapshot({
                target,
                targets,
                type,
                depth: parsedDepth,
            }));
        }

        return timing.measure("workspace.index", () => readProjectWorkspaceTreeSnapshot({
            target,
            fileIndex: projectHandles!.fileIndex,
            targets,
            type,
            depth: parsedDepth,
        }));
    });
});

/**
 * 解析 target 查询参数。
 */
function parseTargets(value: unknown): string[] {
    if (Array.isArray(value)) {
        return value.filter((item): item is string => typeof item === "string" && item.trim().length > 0);
    }
    if (typeof value === "string" && value.trim()) {
        return [value.trim()];
    }
    return [];
}
