import {
    FormAnnotationRequestDtoSchema,
    type FormAnnotationRequestDto,
} from "nbook/shared/dto/ai-form-annotation.dto";
import {FormAnnotationService} from "nbook/server/ai/form-annotation/form-annotation.service";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "AI"
    ],
    "summary": "AI-powered form annotation (currently returns stub)",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "formKind": {
                            "type": "string",
                            "enum": [
                                "chapter_meta",
                                "story_thread",
                                "story_scene"
                            ]
                        },
                        "draft": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/__schema0"
                            }
                        },
                        "instruction": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 8000
                        },
                        "context": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/__schema0"
                            }
                        }
                    },
                    "required": [
                        "formKind",
                        "draft",
                        "instruction"
                    ],
                    "additionalProperties": false,
                    "definitions": {
                        "__schema0": {
                            "anyOf": [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "number"
                                },
                                {
                                    "type": "boolean"
                                },
                                {
                                    "type": "string",
                                    "nullable": true,
                                    "enum": [
                                        null
                                    ]
                                },
                                {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/__schema0"
                                    }
                                },
                                {
                                    "type": "object",
                                    "additionalProperties": {
                                        "$ref": "#/definitions/__schema0"
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "status": {
                                "type": "string",
                                "enum": [
                                    "stub"
                                ]
                            },
                            "nextDraft": {
                                "type": "object",
                                "additionalProperties": {
                                    "$ref": "#/definitions/__schema0"
                                }
                            },
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "formKind": {
                                        "type": "string",
                                        "enum": [
                                            "chapter_meta",
                                            "story_thread",
                                            "story_scene"
                                        ]
                                    },
                                    "title": {
                                        "type": "string"
                                    },
                                    "description": {
                                        "nullable": true,
                                        "type": "string"
                                    },
                                    "fields": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "key": {
                                                    "type": "string"
                                                },
                                                "label": {
                                                    "type": "string"
                                                },
                                                "description": {
                                                    "nullable": true,
                                                    "type": "string"
                                                },
                                                "aiEditable": {
                                                    "type": "boolean"
                                                },
                                                "inlineAnnotation": {
                                                    "type": "boolean"
                                                }
                                            },
                                            "required": [
                                                "key",
                                                "label",
                                                "description",
                                                "aiEditable",
                                                "inlineAnnotation"
                                            ],
                                            "additionalProperties": false
                                        }
                                    }
                                },
                                "required": [
                                    "formKind",
                                    "title",
                                    "description",
                                    "fields"
                                ],
                                "additionalProperties": false
                            },
                            "editableDraft": {
                                "type": "object",
                                "additionalProperties": {
                                    "$ref": "#/definitions/__schema0"
                                }
                            },
                            "workingDraftYaml": {
                                "type": "string"
                            },
                            "notes": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        },
                        "required": [
                            "status",
                            "nextDraft",
                            "schema",
                            "editableDraft",
                            "workingDraftYaml",
                            "notes"
                        ],
                        "additionalProperties": false,
                        "definitions": {
                            "__schema0": {
                                "anyOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "number"
                                    },
                                    {
                                        "type": "boolean"
                                    },
                                    {
                                        "type": "string",
                                        "nullable": true,
                                        "enum": [
                                            null
                                        ]
                                    },
                                    {
                                        "type": "array",
                                        "items": {
                                            "$ref": "#/definitions/__schema0"
                                        }
                                    },
                                    {
                                        "type": "object",
                                        "additionalProperties": {
                                            "$ref": "#/definitions/__schema0"
                                        }
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});

/**
 * AI 表单批注接口。
 * 当前只返回 stub 结果，用于打通前后端草稿流。
 */
export default defineEventHandler(async (event) => {
    const body = await readBody(event);
    const parseResult = FormAnnotationRequestDtoSchema.safeParse(body);
    if (!parseResult.success) {
        throw createError({
            statusCode: 400,
            message: parseResult.error.issues[0]?.message ?? "请求体不合法",
        });
    }

    return new FormAnnotationService().annotate(parseResult.data as FormAnnotationRequestDto);
});
