import type {ConfigItemMeta} from "nbook/server/config/types";

export const CONFIG_VERSION = "config-v1";

export const CONFIG_REGISTRY: ConfigItemMeta[] = [
    {
        key: "auth.enabled",
        scope: "boot",
        effect: "restart-required",
        merge: "replace",
        secret: false,
        description: "是否启用整站鉴权。关闭时管理员接口也退化为本地无鉴权访问。",
    },
    {
        key: "models.default",
        scope: "global-workspace",
        effect: "next-run",
        merge: "replace",
        secret: false,
        description: "默认模型 key，格式为 provider/model。",
    },
    {
        key: "models.providers",
        scope: "global",
        effect: "next-run",
        merge: "replace",
        secret: false,
        description: "全局模型 Provider 列表，Project Config 不能覆盖。",
    },
    {
        key: "models.providers.*.options.apiKey",
        scope: "global",
        effect: "next-run",
        merge: "replace",
        secret: true,
        description: "模型 Provider API Key，只在设置页展示脱敏状态。",
    },
    {
        key: "embedding",
        scope: "global-workspace",
        effect: "next-run",
        merge: "deep-merge",
        secret: false,
        description: "RAG 使用的嵌入服务配置。Global 保存服务地址与凭证，Project 只能覆盖模型名和维度。",
    },
    {
        key: "embedding.apiKey",
        scope: "global",
        effect: "next-run",
        merge: "replace",
        secret: true,
        description: "嵌入服务 API Key，只在设置页展示脱敏状态。",
    },
    {
        key: "agent.defaultProfileKey",
        scope: "global-workspace",
        effect: "next-session",
        merge: "replace",
        secret: false,
        description: "新建 Agent session 默认使用的 profileKey。",
    },
    {
        key: "agent.profileModelDefaults",
        scope: "global-workspace",
        effect: "next-run",
        merge: "deep-merge",
        secret: false,
        description: "所有 Agent Profile 共同继承的模型参数默认值。",
    },
    {
        key: "agent.profileRuntimeDefaults",
        scope: "global-workspace",
        effect: "next-run",
        merge: "deep-merge",
        secret: false,
        description: "所有 Agent Profile 共同继承的摘要、压缩和文件变更提醒运行策略。",
    },
    {
        key: "agent.profiles",
        scope: "global-workspace",
        effect: "next-run",
        merge: "deep-merge",
        secret: false,
        description: "Agent Profile 模型、自定义 settings 与通用运行策略覆盖。",
    },
    {
        key: "agent.visibleModels",
        scope: "global",
        effect: "next-run",
        merge: "replace",
        secret: false,
        description: "Agent 与 Workflow 可以显式选择的模型清单及用途说明。",
    },
    {
        key: "ui.theme",
        scope: "global",
        effect: "hot",
        merge: "replace",
        secret: false,
        description: "Novel IDE 当前主题 ID。可指向内置主题或现存自定义主题。",
    },
    {
        key: "ui.customThemes",
        scope: "global",
        effect: "hot",
        merge: "replace",
        secret: false,
        description: "Novel IDE 用户自定义主题列表，保存调色盘变量覆盖。",
    },
    {
        key: "editor.markdown",
        scope: "global-workspace",
        effect: "hot",
        merge: "deep-merge",
        secret: false,
        description: "Markdown 富文本编辑器显示偏好。",
    },
    {
        key: "editor.monaco",
        scope: "global-workspace",
        effect: "hot",
        merge: "deep-merge",
        secret: false,
        description: "Monaco 源码编辑器显示偏好。",
    },
    {
        key: "web.search",
        scope: "global",
        effect: "next-run",
        merge: "deep-merge",
        secret: false,
        description: "Agent web_search 搜索 provider 顺序、启用状态和非 secret 运行参数。",
    },
    {
        key: "web.search.providers.*.apiKey",
        scope: "global",
        effect: "next-run",
        merge: "replace",
        secret: true,
        description: "Agent Web 搜索 provider API Key，只在设置页展示脱敏状态。",
    },
    {
        key: "web.fetch",
        scope: "global",
        effect: "next-run",
        merge: "deep-merge",
        secret: false,
        description: "Agent web_fetch 的本地抓取限制和外部 provider fallback 策略。",
    },
    {
        key: "history",
        scope: "global-workspace",
        effect: "next-session",
        merge: "deep-merge",
        secret: false,
        description: "工作区文件历史（操作日志）配置。Global 持有总开关 enabled；retentionFullDays / keepDailyLastAfterWindow / autoAcceptEnabled / autoAcceptDays 可被 Project Config 覆盖。改动在项目下次 open 时生效。",
    },
];
