import {getQuery} from "h3";
import {readConfigBootstrap} from "nbook/server/config/config-service";
import {validateConfigWorkspaceQuery} from "nbook/server/config/query";
import {createServerTiming} from "nbook/server/utils/server-timing";
import {withProjectHttpError} from "nbook/server/api/projects/project-http-error";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Config"
    ],
    "summary": "Get lightweight startup config",
    "parameters": [
        {
            "name": "workspaceKind",
            "in": "query",
            "required": true,
            "schema": {
                "default": "novel",
                "type": "string",
                "enum": [
                    "novel",
                    "user-assets"
                ]
            }
        },
        {
            "name": "projectRoot",
            "in": "query",
            "required": false,
            "schema": {
                "type": "string",
                "minLength": 1
            }
        }
    ],
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "modelSettings": {
                                "type": "object",
                                "properties": {
                                    "defaultModelLabel": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "string"
                                    },
                                    "enabledModels": {
                                        "default": [],
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "key": {
                                                    "type": "string",
                                                    "minLength": 1
                                                },
                                                "label": {
                                                    "type": "string",
                                                    "minLength": 1
                                                },
                                                "providerId": {
                                                    "type": "string",
                                                    "minLength": 1,
                                                    "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]*$"
                                                },
                                                "modelId": {
                                                    "type": "string",
                                                    "minLength": 1
                                                },
                                                "input": {
                                                    "default": [
                                                        "text"
                                                    ],
                                                    "minItems": 1,
                                                    "type": "array",
                                                    "items": {
                                                        "type": "string",
                                                        "enum": [
                                                            "text",
                                                            "image"
                                                        ]
                                                    }
                                                },
                                                "contextWindowTokens": {
                                                    "default": null,
                                                    "nullable": true,
                                                    "type": "integer",
                                                    "minimum": 0,
                                                    "exclusiveMinimum": true,
                                                    "maximum": 9007199254740991
                                                }
                                            },
                                            "required": [
                                                "key",
                                                "label",
                                                "providerId",
                                                "modelId",
                                                "input",
                                                "contextWindowTokens"
                                            ],
                                            "additionalProperties": false
                                        }
                                    }
                                },
                                "required": [
                                    "defaultModelLabel",
                                    "enabledModels"
                                ],
                                "additionalProperties": false
                            },
                            "defaultProfileSettings": {
                                "type": "object",
                                "properties": {
                                    "effectiveProfileKey": {
                                        "nullable": true,
                                        "type": "string",
                                        "minLength": 1
                                    }
                                },
                                "required": [
                                    "effectiveProfileKey"
                                ],
                                "additionalProperties": false
                            },
                            "ui": {
                                "type": "object",
                                "properties": {
                                    "theme": {
                                        "default": "sepia",
                                        "type": "string",
                                        "minLength": 1
                                    },
                                    "customThemes": {
                                        "default": [],
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "id": {
                                                    "type": "string",
                                                    "pattern": "^custom-[a-z0-9-]+$"
                                                },
                                                "name": {
                                                    "type": "string",
                                                    "minLength": 1,
                                                    "maxLength": 50
                                                },
                                                "appearance": {
                                                    "type": "string",
                                                    "enum": [
                                                        "light",
                                                        "dark"
                                                    ]
                                                },
                                                "vars": {
                                                    "type": "object",
                                                    "additionalProperties": {
                                                        "type": "string"
                                                    }
                                                }
                                            },
                                            "required": [
                                                "id",
                                                "name",
                                                "appearance",
                                                "vars"
                                            ],
                                            "additionalProperties": false
                                        }
                                    },
                                    "costCurrency": {
                                        "default": "USD",
                                        "type": "string",
                                        "enum": [
                                            "USD",
                                            "CNY"
                                        ]
                                    }
                                },
                                "required": [
                                    "theme",
                                    "customThemes",
                                    "costCurrency"
                                ],
                                "additionalProperties": false
                            }
                        },
                        "required": [
                            "modelSettings",
                            "defaultProfileSettings",
                            "ui"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        }
    }
} as never,
});

/**
 * 读取首页启动所需的轻量配置。
 */
export default defineEventHandler(async (event) => {
    const timing = createServerTiming(event);
    return withProjectHttpError(() => timing.measure(
        "config.bootstrap",
        () => readConfigBootstrap(validateConfigWorkspaceQuery(getQuery(event))),
    ));
});
