import {createError, getQuery} from "h3";
import {exchangeRateService} from "nbook/server/utils/exchange-rate-service";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Config"
    ],
    "summary": "Get cached USD/CNY exchange rate",
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "base": {
                                "type": "string",
                                "enum": [
                                    "USD"
                                ]
                            },
                            "quote": {
                                "type": "string",
                                "enum": [
                                    "CNY"
                                ]
                            },
                            "rate": {
                                "type": "number",
                                "minimum": 0,
                                "exclusiveMinimum": true
                            },
                            "source": {
                                "type": "string",
                                "enum": [
                                    "frankfurter"
                                ]
                            },
                            "fetchedAt": {
                                "type": "string",
                                "minLength": 1
                            },
                            "stale": {
                                "type": "boolean"
                            }
                        },
                        "required": [
                            "base",
                            "quote",
                            "rate",
                            "source",
                            "fetchedAt",
                            "stale"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        }
    }
} as never,
});

/**
 * 读取费用显示使用的汇率；当前只支持 USD -> CNY。
 */
export default defineEventHandler(async (event) => {
    const query = getQuery(event);
    const base = String(query.base ?? "USD").toUpperCase();
    const quote = String(query.quote ?? "CNY").toUpperCase();

    if (base !== "USD" || quote !== "CNY") {
        throw createError({
            statusCode: 400,
            statusMessage: "当前只支持 USD -> CNY 汇率",
        });
    }

    try {
        return await exchangeRateService.rate({base: "USD", quote: "CNY"});
    } catch (error) {
        throw createError({
            statusCode: 502,
            statusMessage: error instanceof Error ? error.message : "刷新汇率失败",
        });
    }
});
