import {getQuery} from "h3";
import {readConfigSnapshot} from "nbook/server/config/config-service";
import {validateConfigWorkspaceQuery} from "nbook/server/config/query";
import {withProjectHttpError} from "nbook/server/api/projects/project-http-error";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Config"
    ],
    "summary": "Get effective runtime config snapshot",
    "parameters": [
        {
            "name": "workspaceKind",
            "in": "query",
            "required": true,
            "schema": {
                "default": "novel",
                "type": "string",
                "enum": [
                    "novel",
                    "user-assets"
                ]
            }
        },
        {
            "name": "projectRoot",
            "in": "query",
            "required": false,
            "schema": {
                "type": "string",
                "minLength": 1
            }
        }
    ],
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "version": {
                                "type": "string",
                                "minLength": 1
                            },
                            "effective": {
                                "type": "object",
                                "additionalProperties": {
                                    "$ref": "#/definitions/__schema0"
                                }
                            },
                            "meta": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "key": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "scope": {
                                            "type": "string",
                                            "enum": [
                                                "boot",
                                                "global",
                                                "global-workspace"
                                            ]
                                        },
                                        "effect": {
                                            "type": "string",
                                            "enum": [
                                                "hot",
                                                "next-run",
                                                "next-session",
                                                "restart-required"
                                            ]
                                        },
                                        "merge": {
                                            "type": "string",
                                            "enum": [
                                                "replace",
                                                "deep-merge"
                                            ]
                                        },
                                        "secret": {
                                            "type": "boolean"
                                        },
                                        "description": {
                                            "type": "string",
                                            "minLength": 1
                                        }
                                    },
                                    "required": [
                                        "key",
                                        "scope",
                                        "effect",
                                        "merge",
                                        "secret",
                                        "description"
                                    ],
                                    "additionalProperties": false
                                }
                            }
                        },
                        "required": [
                            "version",
                            "effective",
                            "meta"
                        ],
                        "additionalProperties": false,
                        "definitions": {
                            "__schema0": {
                                "anyOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "number"
                                    },
                                    {
                                        "type": "boolean"
                                    },
                                    {
                                        "type": "string",
                                        "nullable": true,
                                        "enum": [
                                            null
                                        ]
                                    },
                                    {
                                        "type": "array",
                                        "items": {
                                            "$ref": "#/definitions/__schema0"
                                        }
                                    },
                                    {
                                        "type": "object",
                                        "additionalProperties": {
                                            "$ref": "#/definitions/__schema0"
                                        }
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        }
    }
} as never,
});

/**
 * 读取业务运行使用的最新配置快照。
 */
export default defineEventHandler(async (event) => {
    return withProjectHttpError(() => readConfigSnapshot(validateConfigWorkspaceQuery(getQuery(event))));
});
