export type LlmlintTheme = "system" | "light" | "dark" | "sepia";
export type ResolvedLlmlintTheme = Exclude<LlmlintTheme, "system">;
export type ThemeVars = Record<`--${string}`, string>;

export const LLMLINT_THEME_HOST_CLASS = "llmlint-theme";

export const themeTokens: Record<ResolvedLlmlintTheme, ThemeVars> = {
    light: {
        "--bg-main": "#eef2f5",
        "--bg-panel": "#fbfcfd",
        "--bg-subtle": "#e4ecef",
        "--bg-hover": "#d8e7e6",
        "--bg-input": "#ffffff",
        "--text-main": "#172126",
        "--text-secondary": "#4a5960",
        "--text-muted": "#7a8b91",
        "--text-inverse": "#ffffff",
        "--border-color": "#cbd7db",
        "--border-strong": "#91a5ab",
        "--accent-main": "#0f9f92",
        "--accent-bg": "rgba(15, 159, 146, 0.12)",
        "--accent-text": "#08766d",
        "--accent-pop": "#e85d75",
        "--accent-signal": "#e8aa23",
        "--manga-ink": "#172126",
        "--manga-paper": "#fbfcfd",
        "--manga-dot": "rgba(23, 33, 38, 0.10)",
        "--status-success": "#078477",
        "--status-warning": "#b87500",
        "--status-danger": "#cf3f5a",
        "--shadow-panel": "0 16px 44px rgba(31, 55, 62, 0.15)",
    },
    dark: {
        "--bg-main": "#0d1115",
        "--bg-panel": "#171c21",
        "--bg-subtle": "#20282d",
        "--bg-hover": "#29363a",
        "--bg-input": "#11161a",
        "--text-main": "#f5f3eb",
        "--text-secondary": "#c6d3d0",
        "--text-muted": "#788985",
        "--text-inverse": "#111827",
        "--border-color": "#303b40",
        "--border-strong": "#52646a",
        "--accent-main": "#29c7b7",
        "--accent-bg": "rgba(41, 199, 183, 0.14)",
        "--accent-text": "#5eead4",
        "--accent-pop": "#ff6b86",
        "--accent-signal": "#f6c453",
        "--manga-ink": "#f5f3eb",
        "--manga-paper": "#171c21",
        "--manga-dot": "rgba(245, 243, 235, 0.10)",
        "--status-success": "#42d7c4",
        "--status-warning": "#f6c453",
        "--status-danger": "#ff718b",
        "--shadow-panel": "0 18px 56px rgba(0, 0, 0, 0.42)",
    },
    sepia: {
        "--bg-main": "#f3ead7",
        "--bg-panel": "#fff8e8",
        "--bg-subtle": "#eadfc7",
        "--bg-hover": "#dfcfad",
        "--bg-input": "#fffdf5",
        "--text-main": "#3d2f1e",
        "--text-secondary": "#705c45",
        "--text-muted": "#a8947a",
        "--text-inverse": "#fffaf0",
        "--border-color": "#d7c5a7",
        "--border-strong": "#c3ab87",
        "--accent-main": "#b45309",
        "--accent-bg": "rgba(180, 83, 9, 0.12)",
        "--accent-text": "#92400e",
        "--accent-pop": "#b83f5e",
        "--accent-signal": "#b97912",
        "--manga-ink": "#3d2f1e",
        "--manga-paper": "#fff8e8",
        "--manga-dot": "rgba(61, 47, 30, 0.12)",
        "--status-success": "#4d7c0f",
        "--status-warning": "#b45309",
        "--status-danger": "#b91c1c",
        "--shadow-panel": "0 18px 60px rgba(91, 63, 28, 0.18)",
    },
};

export const themeVarKeys = Object.keys(themeTokens.light) as Array<keyof typeof themeTokens.light>;
