import {
    CreateStoryActRequestDtoSchema,
    CreateStoryChapterRequestDtoSchema,
    CreateStoryDecisionRequestDtoSchema,
    CreateStoryPhaseRequestDtoSchema,
    CreateStoryPromiseRequestDtoSchema,
    CreateStorySceneRequestDtoSchema,
    CreateStoryThreadRequestDtoSchema,
    ReorderStoryPhasesRequestDtoSchema,
    ReorderStoryScenesRequestDtoSchema,
    ReorderStoryThreadsRequestDtoSchema,
    SetPromiseBeatRequestDtoSchema,
    UpdateStoryActRequestDtoSchema,
    UpdateStoryChapterRequestDtoSchema,
    UpdateStoryDecisionRequestDtoSchema,
    UpdateStoryPhaseRequestDtoSchema,
    UpdateStoryPromiseRequestDtoSchema,
    UpdateStoryRequestDtoSchema,
    UpdateStorySceneRequestDtoSchema,
    UpdateStoryThreadRequestDtoSchema,
    type CreateStoryActRequestDto,
    type CreateStoryChapterRequestDto,
    type CreateStoryDecisionRequestDto,
    type CreateStoryPhaseRequestDto,
    type CreateStoryPromiseRequestDto,
    type CreateStorySceneRequestDto,
    type CreateStoryThreadRequestDto,
    type ReorderStoryPhasesRequestDto,
    type ReorderStoryScenesRequestDto,
    type ReorderStoryThreadsRequestDto,
    type SetPromiseBeatRequestDto,
    type UpdateStoryActRequestDto,
    type UpdateStoryChapterRequestDto,
    type UpdateStoryDecisionRequestDto,
    type UpdateStoryPhaseRequestDto,
    type UpdateStoryPromiseRequestDto,
    type UpdateStoryRequestDto,
    type UpdateStorySceneRequestDto,
    type UpdateStoryThreadRequestDto,
} from "nbook/shared/dto/plot.dto";
import type {H3Event} from "h3";
import {PROJECT_PLOT_WORLD_MODULE_TOKEN} from "nbook/server/plot";
import type {PlotFacade} from "nbook/server/plot/facade/plot.facade";
import {parseEntityId, validateBody} from "nbook/server/utils/novel-chapter";
import {requireProjectRefQuery} from "nbook/server/api/projects/project-control-plane";
import {
    activateReadyProjectModule,
    requireActiveReadyProject,
    runReadyProjectOperation,
} from "nbook/server/workspace-files/project-session";
import {withProjectHttpError} from "nbook/server/api/projects/project-http-error";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Plot Scenes"
    ],
    "summary": "Get a story scene's filtered World Engine context via /projects/plot/scenes/:sceneId/world-context",
    "parameters": [
        {
            "name": "sceneId",
            "in": "path",
            "required": true,
            "schema": {
                "type": "string"
            }
        },
        {
            "name": "projectRoot",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "minLength": 1,
                "description": "Project Workspace root, single directory name under Workspace Root"
            },
            "description": "Project Workspace root, single directory name under Workspace Root"
        }
    ],
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "slices": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "string"
                                        },
                                        "time": {
                                            "type": "string"
                                        },
                                        "title": {
                                            "type": "string"
                                        },
                                        "summary": {
                                            "type": "string"
                                        },
                                        "kind": {
                                            "type": "string"
                                        },
                                        "patchCount": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 9007199254740991
                                        }
                                    },
                                    "required": [
                                        "id",
                                        "time",
                                        "title",
                                        "summary",
                                        "kind",
                                        "patchCount"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "subjectStates": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "subjectId": {
                                            "type": "string"
                                        },
                                        "type": {
                                            "type": "string"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "attrs": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "$ref": "#/definitions/__schema0"
                                            }
                                        }
                                    },
                                    "required": [
                                        "subjectId",
                                        "type",
                                        "name",
                                        "attrs"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "unresolvedSubjectIds": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        },
                        "required": [
                            "slices",
                            "subjectStates",
                            "unresolvedSubjectIds"
                        ],
                        "additionalProperties": false,
                        "definitions": {
                            "__schema0": {
                                "anyOf": [
                                    {
                                        "type": "string",
                                        "nullable": true,
                                        "enum": [
                                            null
                                        ]
                                    },
                                    {
                                        "type": "boolean"
                                    },
                                    {
                                        "type": "number"
                                    },
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "array",
                                        "items": {
                                            "$ref": "#/definitions/__schema0"
                                        }
                                    },
                                    {
                                        "type": "object",
                                        "additionalProperties": {
                                            "$ref": "#/definitions/__schema0"
                                        }
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        }
    }
} as never,
});





/**
 * Project Path query 版本的 Plot API，避免把 workspace/<project> 放进 URL path 段。
 */
export default defineEventHandler((event) => withProjectHttpError(() => handleProjectPlotApi(event)));

/**
 * 处理 Project Plot API。外层 handler 只负责把 ProjectSession typed error 转成 HTTP 409。
 */
async function handleProjectPlotApi(event: H3Event): Promise<unknown> {
    const ready = requireActiveReadyProject(requireProjectRefQuery(event));
    return runReadyProjectOperation(ready, async () => {
        const {plot: plotFacade} = await activateReadyProjectModule(ready, PROJECT_PLOT_WORLD_MODULE_TOKEN);
        const segments = readSegments(event);
        const method = event.method.toUpperCase();

        if (method === "GET" && matchSegments(segments, ["story"])) {
            return plotFacade.getStoryDto();
        }
        if (method === "PATCH" && matchSegments(segments, ["story"])) {
            const body = await validateBody<UpdateStoryRequestDto>(event, UpdateStoryRequestDtoSchema);
            return plotFacade.updateStory(body);
        }
        if (method === "GET" && matchSegments(segments, ["tree"])) {
            return plotFacade.getPlotTree();
        }
        if (method === "GET" && matchSegments(segments, ["workbench"])) {
            return plotFacade.getPlotWorkbench();
        }
        if (method === "GET" && matchSegments(segments, ["chapter"])) {
            return plotFacade.getChapterPlotDetailDto(requireChapterIdQuery(event));
        }
        if (method === "GET" && matchSegments(segments, ["chapter-writer-brief"])) {
            return plotFacade.getChapterWriterBrief(requireChapterIdQuery(event), readBriefModeQuery(event));
        }

        if (segments[0] === "phases") {
            return handlePhases(plotFacade, event, method, segments);
        }
        if (segments[0] === "acts") {
            return handleActs(plotFacade, event, method, segments);
        }
        if (segments[0] === "chapters") {
            return handleChapters(plotFacade, event, method, segments);
        }
        if (segments[0] === "threads") {
            return handleThreads(plotFacade, event, method, segments);
        }
        if (segments[0] === "scenes") {
            return handleScenes(plotFacade, event, method, segments);
        }
        if (segments[0] === "promises") {
            return handlePromises(plotFacade, event, method, segments);
        }
        if (segments[0] === "decisions") {
            return handleDecisions(plotFacade, event, method, segments);
        }

        throw createError({statusCode: 404, message: "未知 Project Plot API"});
    });
}

/** 承载树 Act(卷)CRUD。 */
async function handleActs(plotFacade: PlotFacade, event: H3Event, method: string, segments: string[]): Promise<unknown> {
    if (method === "POST" && matchSegments(segments, ["acts"])) {
        const body = await validateBody<CreateStoryActRequestDto>(event, CreateStoryActRequestDtoSchema);
        return plotFacade.createStoryAct(body);
    }
    if (segments.length === 2) {
        const actId = parseEntityId("actId", segments[1] ?? "");
        if (method === "GET") return plotFacade.getStoryActDto(actId);
        if (method === "PATCH") {
            const body = await validateBody<UpdateStoryActRequestDto>(event, UpdateStoryActRequestDtoSchema);
            return plotFacade.updateStoryAct(actId, body);
        }
        if (method === "DELETE") return plotFacade.deleteStoryAct(actId);
    }
    throw createError({statusCode: 404, message: "未知 Project Act API"});
}

/** 承载树 Chapter(章)CRUD,含 ChapterBrief 字段更新。 */
async function handleChapters(plotFacade: PlotFacade, event: H3Event, method: string, segments: string[]): Promise<unknown> {
    if (method === "POST" && matchSegments(segments, ["chapters"])) {
        const body = await validateBody<CreateStoryChapterRequestDto>(event, CreateStoryChapterRequestDtoSchema);
        return plotFacade.createStoryChapter(body);
    }
    if (segments.length === 2) {
        const chapterId = parseEntityId("chapterId", segments[1] ?? "");
        if (method === "GET") return plotFacade.getStoryChapterDto(chapterId);
        if (method === "PATCH") {
            const body = await validateBody<UpdateStoryChapterRequestDto>(event, UpdateStoryChapterRequestDtoSchema);
            return plotFacade.updateStoryChapter(chapterId, body);
        }
        if (method === "DELETE") return plotFacade.deleteStoryChapter(chapterId);
    }
    // GET /chapters/:id/prose:列出通过 frontmatter `chapter: <name>` 反指本章的正文节点。
    if (method === "GET" && segments.length === 3 && segments[2] === "prose") {
        const chapterId = parseEntityId("chapterId", segments[1] ?? "");
        const chapter = await plotFacade.getStoryChapterDto(chapterId);
        return plotFacade.findProseForChapter(chapter.name);
    }
    throw createError({statusCode: 404, message: "未知 Project Chapter API"});
}

async function handlePhases(plotFacade: PlotFacade, event: H3Event, method: string, segments: string[]): Promise<unknown> {
    if (method === "POST" && matchSegments(segments, ["phases"])) {
        const body = await validateBody<CreateStoryPhaseRequestDto>(event, CreateStoryPhaseRequestDtoSchema);
        return plotFacade.createStoryPhase(body);
    }
    if (method === "POST" && matchSegments(segments, ["phases", "reorder"])) {
        const body = await validateBody<ReorderStoryPhasesRequestDto>(event, ReorderStoryPhasesRequestDtoSchema);
        return plotFacade.reorderStoryPhases(body);
    }
    if (segments.length === 2) {
        const phaseId = parseEntityId("phaseId", segments[1] ?? "");
        if (method === "GET") return plotFacade.getStoryPhaseDto(phaseId);
        if (method === "PATCH") {
            const body = await validateBody<UpdateStoryPhaseRequestDto>(event, UpdateStoryPhaseRequestDtoSchema);
            return plotFacade.updateStoryPhase(phaseId, body);
        }
        if (method === "DELETE") return plotFacade.deleteStoryPhase(phaseId);
    }
    throw createError({statusCode: 404, message: "未知 Project Phase API"});
}

async function handleThreads(plotFacade: PlotFacade, event: H3Event, method: string, segments: string[]): Promise<unknown> {
    if (method === "POST" && matchSegments(segments, ["threads"])) {
        const body = await validateBody<CreateStoryThreadRequestDto>(event, CreateStoryThreadRequestDtoSchema);
        return plotFacade.createStoryThread(body);
    }
    if (method === "POST" && matchSegments(segments, ["threads", "reorder"])) {
        const body = await validateBody<ReorderStoryThreadsRequestDto>(event, ReorderStoryThreadsRequestDtoSchema);
        return plotFacade.reorderStoryThreads(body);
    }
    if (segments.length === 2) {
        const threadId = parseEntityId("threadId", segments[1] ?? "");
        if (method === "GET") return plotFacade.getStoryThreadDetailDto(threadId);
        if (method === "PATCH") {
            const body = await validateBody<UpdateStoryThreadRequestDto>(event, UpdateStoryThreadRequestDtoSchema);
            return plotFacade.updateStoryThread(threadId, body);
        }
        if (method === "DELETE") return plotFacade.deleteStoryThread(threadId);
    }
    throw createError({statusCode: 404, message: "未知 Project Thread API"});
}

async function handleScenes(plotFacade: PlotFacade, event: H3Event, method: string, segments: string[]): Promise<unknown> {
    if (method === "POST" && matchSegments(segments, ["scenes"])) {
        const body = await validateBody<CreateStorySceneRequestDto>(event, CreateStorySceneRequestDtoSchema);
        return plotFacade.createStoryScene(body);
    }
    if (method === "POST" && matchSegments(segments, ["scenes", "reorder"])) {
        const body = await validateBody<ReorderStoryScenesRequestDto>(event, ReorderStoryScenesRequestDtoSchema);
        return plotFacade.reorderStoryScenes(body);
    }
    if (method === "GET" && segments.length === 3 && segments[2] === "world-context") {
        const sceneId = parseEntityId("sceneId", segments[1] ?? "");
        return plotFacade.getSceneWorldContext(sceneId);
    }
    if (segments.length === 2) {
        const sceneId = parseEntityId("sceneId", segments[1] ?? "");
        if (method === "GET") return plotFacade.getStorySceneDetailDto(sceneId);
        if (method === "PATCH") {
            const body = await validateBody<UpdateStorySceneRequestDto>(event, UpdateStorySceneRequestDtoSchema);
            return plotFacade.updateStoryScene(sceneId, body);
        }
        if (method === "DELETE") return plotFacade.deleteStoryScene(sceneId);
    }
    throw createError({statusCode: 404, message: "未知 Project Scene API"});
}

/** 规划层 Promise(读者债务账本)CRUD 与 beat 维护。物理删除只给 UI/人工,Agent 走 abandon。 */
async function handlePromises(plotFacade: PlotFacade, event: H3Event, method: string, segments: string[]): Promise<unknown> {
    if (method === "GET" && matchSegments(segments, ["promises"])) {
        return plotFacade.listStoryPromises();
    }
    if (method === "POST" && matchSegments(segments, ["promises"])) {
        const body = await validateBody<CreateStoryPromiseRequestDto>(event, CreateStoryPromiseRequestDtoSchema);
        return plotFacade.createStoryPromise(body);
    }
    if (segments.length === 2) {
        const promiseId = parseEntityId("promiseId", segments[1] ?? "");
        if (method === "GET") return plotFacade.getStoryPromiseDetailDto(promiseId);
        if (method === "PATCH") {
            const body = await validateBody<UpdateStoryPromiseRequestDto>(event, UpdateStoryPromiseRequestDtoSchema);
            return plotFacade.updateStoryPromise(promiseId, body);
        }
        if (method === "DELETE") return plotFacade.deleteStoryPromise(promiseId);
    }
    // PUT /promises/:id/beats:upsert 一条 beat(同场同线仅一条);DELETE /promises/:id/beats/:sceneId:移除并跑回退检查。
    if (method === "PUT" && segments.length === 3 && segments[2] === "beats") {
        const promiseId = parseEntityId("promiseId", segments[1] ?? "");
        const body = await validateBody<SetPromiseBeatRequestDto>(event, SetPromiseBeatRequestDtoSchema);
        return plotFacade.setPromiseBeat(promiseId, body);
    }
    if (method === "DELETE" && segments.length === 4 && segments[2] === "beats") {
        const promiseId = parseEntityId("promiseId", segments[1] ?? "");
        const sceneId = parseEntityId("sceneId", segments[3] ?? "");
        return plotFacade.removePromiseBeat(promiseId, sceneId);
    }
    throw createError({statusCode: 404, message: "未知 Project Promise API"});
}

/** 规划层 Decision(ADR 式决策记录)CRUD。decide/drop/supersede/reopen 都走 PATCH 的 status 直改,转换与不变式在服务层。 */
async function handleDecisions(plotFacade: PlotFacade, event: H3Event, method: string, segments: string[]): Promise<unknown> {
    if (method === "GET" && matchSegments(segments, ["decisions"])) {
        return plotFacade.listStoryDecisions();
    }
    if (method === "POST" && matchSegments(segments, ["decisions"])) {
        const body = await validateBody<CreateStoryDecisionRequestDto>(event, CreateStoryDecisionRequestDtoSchema);
        return plotFacade.createStoryDecision(body);
    }
    if (segments.length === 2) {
        const decisionId = parseEntityId("decisionId", segments[1] ?? "");
        if (method === "GET") return plotFacade.getStoryDecisionDto(decisionId);
        if (method === "PATCH") {
            const body = await validateBody<UpdateStoryDecisionRequestDto>(event, UpdateStoryDecisionRequestDtoSchema);
            return plotFacade.updateStoryDecision(decisionId, body);
        }
        if (method === "DELETE") return plotFacade.deleteStoryDecision(decisionId);
    }
    throw createError({statusCode: 404, message: "未知 Project Decision API"});
}

function readSegments(event: H3Event): string[] {
    const rawSegments = event.context.params?.segments;
    const segments = Array.isArray(rawSegments) ? rawSegments : typeof rawSegments === "string" ? rawSegments.split("/") : [];
    return segments.map((segment) => decodeURIComponent(segment)).filter(Boolean);
}

function matchSegments(left: string[], right: string[]): boolean {
    return left.length === right.length && left.every((segment, index) => segment === right[index]);
}

function requireChapterIdQuery(event: H3Event): number {
    const value = getQuery(event).chapterId;
    const text = typeof value === "string" ? value.trim() : "";
    if (!text) {
        throw createError({statusCode: 400, message: "chapterId query 不能为空"});
    }
    return parseEntityId("chapterId", text);
}

/** 读取 brief 防全知模式 query;缺省或非法一律回落 autonomous。 */
function readBriefModeQuery(event: H3Event): "autonomous" | "curated" {
    return getQuery(event).mode === "curated" ? "curated" : "autonomous";
}
