import {debugProjectRag} from "nbook/server/rag/project-rag-visualization";
import {ProjectRagDebugRequestDtoSchema, ProjectRagDebugResultDtoSchema} from "nbook/shared/dto/project-rag.dto";
import {withProjectRagTarget} from "nbook/server/api/projects/rag/project-rag-http-target";
import {validateBody} from "nbook/server/utils/novel-chapter";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Project RAG"
    ],
    "summary": "Run Project RAG debug operations",
    "parameters": [
        {
            "name": "projectRoot",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "minLength": 1,
                "description": "Project Workspace root, single directory name under Workspace Root"
            },
            "description": "Project Workspace root, single directory name under Workspace Root"
        }
    ],
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "oneOf": [
                        {
                            "type": "object",
                            "properties": {
                                "action": {
                                    "type": "string",
                                    "enum": [
                                        "mark-dirty"
                                    ]
                                },
                                "subjectPath": {
                                    "type": "string",
                                    "minLength": 1,
                                    "pattern": "^simulation\\/subjects\\/[^/]+$"
                                },
                                "sources": {
                                    "minItems": 1,
                                    "type": "array",
                                    "items": {
                                        "type": "string",
                                        "enum": [
                                            "events",
                                            "memory"
                                        ]
                                    }
                                }
                            },
                            "required": [
                                "action"
                            ],
                            "additionalProperties": false
                        },
                        {
                            "type": "object",
                            "properties": {
                                "action": {
                                    "type": "string",
                                    "enum": [
                                        "delete-subject-index"
                                    ]
                                },
                                "subjectPath": {
                                    "type": "string",
                                    "minLength": 1,
                                    "pattern": "^simulation\\/subjects\\/[^/]+$"
                                }
                            },
                            "required": [
                                "action",
                                "subjectPath"
                            ],
                            "additionalProperties": false
                        },
                        {
                            "type": "object",
                            "properties": {
                                "action": {
                                    "type": "string",
                                    "enum": [
                                        "clear-index-cache"
                                    ]
                                }
                            },
                            "required": [
                                "action"
                            ],
                            "additionalProperties": false
                        },
                        {
                            "type": "object",
                            "properties": {
                                "action": {
                                    "type": "string",
                                    "enum": [
                                        "clear-index-cache-and-rebuild"
                                    ]
                                },
                                "subjectPath": {
                                    "type": "string",
                                    "minLength": 1,
                                    "pattern": "^simulation\\/subjects\\/[^/]+$"
                                }
                            },
                            "required": [
                                "action"
                            ],
                            "additionalProperties": false
                        }
                    ]
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "projectRoot": {
                                "type": "string",
                                "minLength": 1
                            },
                            "action": {
                                "type": "string",
                                "enum": [
                                    "mark-dirty",
                                    "delete-subject-index",
                                    "clear-index-cache",
                                    "clear-index-cache-and-rebuild"
                                ]
                            },
                            "message": {
                                "type": "string"
                            },
                            "rebuild": {
                                "type": "object",
                                "properties": {
                                    "projectRoot": {
                                        "type": "string",
                                        "minLength": 1
                                    },
                                    "rebuiltSubjects": {
                                        "type": "integer",
                                        "minimum": 0,
                                        "maximum": 9007199254740991
                                    },
                                    "skippedSubjects": {
                                        "type": "integer",
                                        "minimum": 0,
                                        "maximum": 9007199254740991
                                    },
                                    "results": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "subjectPath": {
                                                    "type": "string",
                                                    "minLength": 1,
                                                    "pattern": "^simulation\\/subjects\\/[^/]+$"
                                                },
                                                "ok": {
                                                    "type": "boolean"
                                                },
                                                "message": {
                                                    "nullable": true,
                                                    "type": "string"
                                                }
                                            },
                                            "required": [
                                                "subjectPath",
                                                "ok",
                                                "message"
                                            ],
                                            "additionalProperties": false
                                        }
                                    }
                                },
                                "required": [
                                    "projectRoot",
                                    "rebuiltSubjects",
                                    "skippedSubjects",
                                    "results"
                                ],
                                "additionalProperties": false
                            }
                        },
                        "required": [
                            "projectRoot",
                            "action",
                            "message"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});





/**
 * 执行 RAG Inspector 调试操作。
 */
export default defineEventHandler((event) => withProjectRagTarget(event, async (target) => {
    const body = await validateBody(event, ProjectRagDebugRequestDtoSchema);
    const result = await debugProjectRag(target, body);
    return ProjectRagDebugResultDtoSchema.parse(result);
}));
