import {ProjectRagEventDeleteRequestDtoSchema, ProjectRagSubjectDtoSchema} from "nbook/shared/dto/project-rag.dto";
import {deleteProjectRagEvent} from "nbook/server/rag/project-rag-visualization";
import {withProjectRagTarget} from "nbook/server/api/projects/rag/project-rag-http-target";
import {validateBody} from "nbook/server/utils/novel-chapter";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Project RAG"
    ],
    "summary": "Delete a subject event",
    "parameters": [
        {
            "name": "projectRoot",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "minLength": 1,
                "description": "Project Workspace root, single directory name under Workspace Root"
            },
            "description": "Project Workspace root, single directory name under Workspace Root"
        }
    ],
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "subjectPath": {
                            "type": "string",
                            "minLength": 1,
                            "pattern": "^simulation\\/subjects\\/[^/]+$"
                        },
                        "index": {
                            "type": "integer",
                            "minimum": 0,
                            "maximum": 9007199254740991
                        }
                    },
                    "required": [
                        "subjectPath",
                        "index"
                    ],
                    "additionalProperties": false
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "projectRoot": {
                                "type": "string",
                                "minLength": 1
                            },
                            "subjectPath": {
                                "type": "string",
                                "minLength": 1,
                                "pattern": "^simulation\\/subjects\\/[^/]+$"
                            },
                            "subjectId": {
                                "type": "string",
                                "minLength": 1
                            },
                            "events": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "line": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "exclusiveMinimum": true,
                                            "maximum": 9007199254740991
                                        },
                                        "tick": {
                                            "type": "string"
                                        },
                                        "time": {
                                            "type": "string"
                                        },
                                        "text": {
                                            "type": "string",
                                            "minLength": 1
                                        }
                                    },
                                    "required": [
                                        "line",
                                        "text"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "memories": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "line": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "exclusiveMinimum": true,
                                            "maximum": 9007199254740991
                                        },
                                        "topic": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "aliases": {
                                            "type": "array",
                                            "items": {
                                                "type": "string",
                                                "minLength": 1
                                            }
                                        },
                                        "view": {
                                            "type": "string",
                                            "minLength": 1
                                        }
                                    },
                                    "required": [
                                        "line",
                                        "topic",
                                        "view"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "sourceStatuses": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "source": {
                                            "type": "string",
                                            "enum": [
                                                "events",
                                                "memory"
                                            ]
                                        },
                                        "status": {
                                            "type": "string",
                                            "enum": [
                                                "synced",
                                                "dirty",
                                                "error",
                                                "not_indexed",
                                                "unknown"
                                            ]
                                        },
                                        "recordCount": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 9007199254740991
                                        },
                                        "indexedAt": {
                                            "nullable": true,
                                            "type": "string"
                                        },
                                        "lastError": {
                                            "nullable": true,
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "source",
                                        "status",
                                        "recordCount",
                                        "indexedAt",
                                        "lastError"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "errors": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "source": {
                                            "type": "string",
                                            "enum": [
                                                "events",
                                                "memory"
                                            ]
                                        },
                                        "message": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "source",
                                        "message"
                                    ],
                                    "additionalProperties": false
                                }
                            }
                        },
                        "required": [
                            "projectRoot",
                            "subjectPath",
                            "subjectId",
                            "events",
                            "memories",
                            "sourceStatuses",
                            "errors"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});





/**
 * 删除 subject event。
 */
export default defineEventHandler((event) => withProjectRagTarget(event, async (target) => {
    const body = await validateBody(event, ProjectRagEventDeleteRequestDtoSchema);
    const result = await deleteProjectRagEvent(target, body);
    return ProjectRagSubjectDtoSchema.parse(result);
}));
