import {readProjectRagInspector} from "nbook/server/rag/project-rag-visualization";
import {ProjectRagInspectorDtoSchema, ProjectRagInspectorRequestDtoSchema} from "nbook/shared/dto/project-rag.dto";
import {withProjectRagTarget} from "nbook/server/api/projects/rag/project-rag-http-target";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Project RAG"
    ],
    "summary": "Read Project RAG inspector metadata and vector previews",
    "parameters": [
        {
            "name": "projectRoot",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "minLength": 1,
                "description": "Project Workspace root, single directory name under Workspace Root"
            },
            "description": "Project Workspace root, single directory name under Workspace Root"
        },
        {
            "name": "subjectPath",
            "in": "query",
            "required": false,
            "schema": {
                "description": "Project-relative subject path, for example simulation/subjects/<subject-id>",
                "type": "string",
                "minLength": 1
            },
            "description": "Project-relative subject path, for example simulation/subjects/<subject-id>"
        },
        {
            "name": "sources",
            "in": "query",
            "required": false,
            "schema": {
                "description": "Comma-separated source filters: events,memory",
                "type": "string"
            },
            "description": "Comma-separated source filters: events,memory"
        },
        {
            "name": "limit",
            "in": "query",
            "required": false,
            "schema": {
                "description": "Chunk limit",
                "anyOf": [
                    {
                        "type": "string",
                        "enum": [
                            "100"
                        ]
                    },
                    {
                        "type": "string",
                        "enum": [
                            "200"
                        ]
                    },
                    {
                        "type": "string",
                        "enum": [
                            "500"
                        ]
                    }
                ]
            },
            "description": "Chunk limit"
        }
    ],
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "projectRoot": {
                                "type": "string",
                                "minLength": 1
                            },
                            "selectedSubjectPath": {
                                "nullable": true,
                                "type": "string",
                                "minLength": 1,
                                "pattern": "^simulation\\/subjects\\/[^/]+$"
                            },
                            "sourceFilter": {
                                "minItems": 1,
                                "type": "array",
                                "items": {
                                    "type": "string",
                                    "enum": [
                                        "events",
                                        "memory"
                                    ]
                                }
                            },
                            "limit": {
                                "anyOf": [
                                    {
                                        "type": "number",
                                        "enum": [
                                            100
                                        ]
                                    },
                                    {
                                        "type": "number",
                                        "enum": [
                                            200
                                        ]
                                    },
                                    {
                                        "type": "number",
                                        "enum": [
                                            500
                                        ]
                                    }
                                ]
                            },
                            "embedding": {
                                "type": "object",
                                "properties": {
                                    "enabled": {
                                        "type": "boolean"
                                    },
                                    "provider": {
                                        "type": "string"
                                    },
                                    "model": {
                                        "nullable": true,
                                        "type": "string"
                                    },
                                    "dimensions": {
                                        "nullable": true,
                                        "type": "integer",
                                        "minimum": 0,
                                        "exclusiveMinimum": true,
                                        "maximum": 9007199254740991
                                    },
                                    "baseURLConfigured": {
                                        "type": "boolean"
                                    },
                                    "baseURLLabel": {
                                        "nullable": true,
                                        "type": "string"
                                    },
                                    "apiKeyConfigured": {
                                        "type": "boolean"
                                    }
                                },
                                "required": [
                                    "enabled",
                                    "provider",
                                    "model",
                                    "dimensions",
                                    "baseURLConfigured",
                                    "baseURLLabel",
                                    "apiKeyConfigured"
                                ],
                                "additionalProperties": false
                            },
                            "index": {
                                "type": "object",
                                "properties": {
                                    "dbExists": {
                                        "type": "boolean"
                                    },
                                    "schemaVersion": {
                                        "nullable": true,
                                        "type": "string"
                                    },
                                    "embeddingProvider": {
                                        "nullable": true,
                                        "type": "string"
                                    },
                                    "embeddingModel": {
                                        "nullable": true,
                                        "type": "string"
                                    },
                                    "embeddingDimensions": {
                                        "nullable": true,
                                        "type": "integer",
                                        "minimum": 0,
                                        "exclusiveMinimum": true,
                                        "maximum": 9007199254740991
                                    },
                                    "metaMatchesEffectiveConfig": {
                                        "nullable": true,
                                        "type": "boolean"
                                    },
                                    "readError": {
                                        "nullable": true,
                                        "type": "string"
                                    },
                                    "sourceCount": {
                                        "type": "integer",
                                        "minimum": 0,
                                        "maximum": 9007199254740991
                                    },
                                    "chunkCount": {
                                        "type": "integer",
                                        "minimum": 0,
                                        "maximum": 9007199254740991
                                    },
                                    "vectorCount": {
                                        "type": "integer",
                                        "minimum": 0,
                                        "maximum": 9007199254740991
                                    }
                                },
                                "required": [
                                    "dbExists",
                                    "schemaVersion",
                                    "embeddingProvider",
                                    "embeddingModel",
                                    "embeddingDimensions",
                                    "metaMatchesEffectiveConfig",
                                    "readError",
                                    "sourceCount",
                                    "chunkCount",
                                    "vectorCount"
                                ],
                                "additionalProperties": false
                            },
                            "subjects": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "subjectPath": {
                                            "type": "string",
                                            "minLength": 1,
                                            "pattern": "^simulation\\/subjects\\/[^/]+$"
                                        },
                                        "subjectId": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "metadata": {
                                            "type": "object",
                                            "properties": {
                                                "id": {
                                                    "nullable": true,
                                                    "type": "string",
                                                    "minLength": 1
                                                },
                                                "name": {
                                                    "nullable": true,
                                                    "type": "string",
                                                    "minLength": 1
                                                },
                                                "kind": {
                                                    "nullable": true,
                                                    "type": "string",
                                                    "minLength": 1
                                                },
                                                "profile": {
                                                    "nullable": true,
                                                    "type": "string",
                                                    "minLength": 1
                                                },
                                                "controlledBy": {
                                                    "nullable": true,
                                                    "type": "string",
                                                    "minLength": 1
                                                },
                                                "canonicalSource": {
                                                    "nullable": true,
                                                    "type": "string",
                                                    "minLength": 1
                                                },
                                                "frontmatterError": {
                                                    "nullable": true,
                                                    "type": "string"
                                                }
                                            },
                                            "required": [
                                                "id",
                                                "name",
                                                "kind",
                                                "profile",
                                                "controlledBy",
                                                "canonicalSource",
                                                "frontmatterError"
                                            ],
                                            "additionalProperties": false
                                        },
                                        "eventCount": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 9007199254740991
                                        },
                                        "memoryCount": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 9007199254740991
                                        },
                                        "subjectFileExists": {
                                            "type": "boolean"
                                        },
                                        "soulFileExists": {
                                            "type": "boolean"
                                        },
                                        "mindFileExists": {
                                            "type": "boolean"
                                        },
                                        "stateFileExists": {
                                            "type": "boolean"
                                        },
                                        "sourceStatuses": {
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "source": {
                                                        "type": "string",
                                                        "enum": [
                                                            "events",
                                                            "memory"
                                                        ]
                                                    },
                                                    "status": {
                                                        "type": "string",
                                                        "enum": [
                                                            "synced",
                                                            "dirty",
                                                            "error",
                                                            "not_indexed",
                                                            "unknown"
                                                        ]
                                                    },
                                                    "recordCount": {
                                                        "type": "integer",
                                                        "minimum": 0,
                                                        "maximum": 9007199254740991
                                                    },
                                                    "indexedAt": {
                                                        "nullable": true,
                                                        "type": "string"
                                                    },
                                                    "lastError": {
                                                        "nullable": true,
                                                        "type": "string"
                                                    }
                                                },
                                                "required": [
                                                    "source",
                                                    "status",
                                                    "recordCount",
                                                    "indexedAt",
                                                    "lastError"
                                                ],
                                                "additionalProperties": false
                                            }
                                        },
                                        "errors": {
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "source": {
                                                        "type": "string",
                                                        "enum": [
                                                            "events",
                                                            "memory"
                                                        ]
                                                    },
                                                    "message": {
                                                        "type": "string"
                                                    }
                                                },
                                                "required": [
                                                    "source",
                                                    "message"
                                                ],
                                                "additionalProperties": false
                                            }
                                        }
                                    },
                                    "required": [
                                        "subjectPath",
                                        "subjectId",
                                        "metadata",
                                        "eventCount",
                                        "memoryCount",
                                        "subjectFileExists",
                                        "soulFileExists",
                                        "mindFileExists",
                                        "stateFileExists",
                                        "sourceStatuses",
                                        "errors"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "selectedSubject": {
                                "nullable": true,
                                "type": "object",
                                "properties": {
                                    "subjectPath": {
                                        "type": "string",
                                        "minLength": 1,
                                        "pattern": "^simulation\\/subjects\\/[^/]+$"
                                    },
                                    "subjectId": {
                                        "type": "string",
                                        "minLength": 1
                                    },
                                    "sourceStatuses": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "source": {
                                                    "type": "string",
                                                    "enum": [
                                                        "events",
                                                        "memory"
                                                    ]
                                                },
                                                "status": {
                                                    "type": "string",
                                                    "enum": [
                                                        "synced",
                                                        "dirty",
                                                        "error",
                                                        "not_indexed",
                                                        "unknown"
                                                    ]
                                                },
                                                "recordCount": {
                                                    "type": "integer",
                                                    "minimum": 0,
                                                    "maximum": 9007199254740991
                                                },
                                                "indexedAt": {
                                                    "nullable": true,
                                                    "type": "string"
                                                },
                                                "lastError": {
                                                    "nullable": true,
                                                    "type": "string"
                                                }
                                            },
                                            "required": [
                                                "source",
                                                "status",
                                                "recordCount",
                                                "indexedAt",
                                                "lastError"
                                            ],
                                            "additionalProperties": false
                                        }
                                    },
                                    "chunkSourceCounts": {
                                        "type": "object",
                                        "properties": {
                                            "events": {
                                                "type": "integer",
                                                "minimum": 0,
                                                "maximum": 9007199254740991
                                            },
                                            "memory": {
                                                "type": "integer",
                                                "minimum": 0,
                                                "maximum": 9007199254740991
                                            }
                                        },
                                        "required": [
                                            "events",
                                            "memory"
                                        ],
                                        "additionalProperties": false
                                    },
                                    "chunks": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "id": {
                                                    "type": "integer",
                                                    "minimum": 0,
                                                    "exclusiveMinimum": true,
                                                    "maximum": 9007199254740991
                                                },
                                                "source": {
                                                    "type": "string",
                                                    "enum": [
                                                        "events",
                                                        "memory"
                                                    ]
                                                },
                                                "sourcePath": {
                                                    "type": "string"
                                                },
                                                "sourceKey": {
                                                    "type": "string"
                                                },
                                                "chunkIndex": {
                                                    "type": "integer",
                                                    "minimum": 0,
                                                    "maximum": 9007199254740991
                                                },
                                                "topic": {
                                                    "nullable": true,
                                                    "type": "string"
                                                },
                                                "tick": {
                                                    "nullable": true,
                                                    "type": "string"
                                                },
                                                "time": {
                                                    "nullable": true,
                                                    "type": "string"
                                                },
                                                "text": {
                                                    "type": "string"
                                                },
                                                "contentHash": {
                                                    "type": "string"
                                                },
                                                "createdAt": {
                                                    "type": "string"
                                                },
                                                "vector": {
                                                    "type": "object",
                                                    "properties": {
                                                        "exists": {
                                                            "type": "boolean"
                                                        },
                                                        "dimensions": {
                                                            "nullable": true,
                                                            "type": "integer",
                                                            "minimum": 0,
                                                            "exclusiveMinimum": true,
                                                            "maximum": 9007199254740991
                                                        },
                                                        "preview": {
                                                            "type": "array",
                                                            "items": {
                                                                "type": "number"
                                                            }
                                                        },
                                                        "previewDimensions": {
                                                            "type": "integer",
                                                            "minimum": 0,
                                                            "maximum": 9007199254740991
                                                        },
                                                        "embeddingProvider": {
                                                            "nullable": true,
                                                            "type": "string"
                                                        },
                                                        "embeddingModel": {
                                                            "nullable": true,
                                                            "type": "string"
                                                        },
                                                        "embeddingDimensions": {
                                                            "nullable": true,
                                                            "type": "integer",
                                                            "minimum": 0,
                                                            "exclusiveMinimum": true,
                                                            "maximum": 9007199254740991
                                                        },
                                                        "embeddingIndexedAt": {
                                                            "nullable": true,
                                                            "type": "string"
                                                        }
                                                    },
                                                    "required": [
                                                        "exists",
                                                        "dimensions",
                                                        "preview",
                                                        "previewDimensions",
                                                        "embeddingProvider",
                                                        "embeddingModel",
                                                        "embeddingDimensions",
                                                        "embeddingIndexedAt"
                                                    ],
                                                    "additionalProperties": false
                                                }
                                            },
                                            "required": [
                                                "id",
                                                "source",
                                                "sourcePath",
                                                "sourceKey",
                                                "chunkIndex",
                                                "topic",
                                                "tick",
                                                "time",
                                                "text",
                                                "contentHash",
                                                "createdAt",
                                                "vector"
                                            ],
                                            "additionalProperties": false
                                        }
                                    },
                                    "chunksTruncated": {
                                        "type": "boolean"
                                    }
                                },
                                "required": [
                                    "subjectPath",
                                    "subjectId",
                                    "sourceStatuses",
                                    "chunkSourceCounts",
                                    "chunks",
                                    "chunksTruncated"
                                ],
                                "additionalProperties": false
                            }
                        },
                        "required": [
                            "projectRoot",
                            "selectedSubjectPath",
                            "sourceFilter",
                            "limit",
                            "embedding",
                            "index",
                            "subjects",
                            "selectedSubject"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        }
    }
} as never,
});





/**
 * 读取 Project RAG Inspector 的索引与向量元数据快照。
 */
export default defineEventHandler((event) => withProjectRagTarget(event, async (target) => {
    const query = getQuery(event);
    const sources = typeof query.sources === "string"
        ? query.sources.split(",").map((item) => item.trim()).filter(Boolean)
        : undefined;
    const limit = typeof query.limit === "string" && query.limit.trim()
        ? Number(query.limit)
        : undefined;
    const input = ProjectRagInspectorRequestDtoSchema.parse({
        subjectPath: typeof query.subjectPath === "string" && query.subjectPath.trim() ? query.subjectPath.trim() : undefined,
        sources,
        limit,
    });
    const result = await readProjectRagInspector(target, input);
    return ProjectRagInspectorDtoSchema.parse(result);
}));
