import {modelLibrary} from "nbook/server/models/model-library";
import type {ModelLibraryDto} from "nbook/shared/dto/app-settings.dto";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Config"
    ],
    "summary": "Read the NeuroBook model library",
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "models": {
                                "default": [],
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "name": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "source": {
                                            "type": "string",
                                            "minLength": 1,
                                            "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]*$"
                                        },
                                        "reasoning": {
                                            "type": "boolean"
                                        },
                                        "thinkingLevelMap": {
                                            "default": null,
                                            "nullable": true,
                                            "type": "object",
                                            "additionalProperties": {
                                                "nullable": true,
                                                "type": "string"
                                            }
                                        },
                                        "input": {
                                            "minItems": 1,
                                            "type": "array",
                                            "items": {
                                                "type": "string",
                                                "enum": [
                                                    "text",
                                                    "image"
                                                ]
                                            }
                                        },
                                        "contextWindowTokens": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "exclusiveMinimum": true,
                                            "maximum": 9007199254740991
                                        },
                                        "maxTokens": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "exclusiveMinimum": true,
                                            "maximum": 9007199254740991
                                        }
                                    },
                                    "required": [
                                        "id",
                                        "name",
                                        "source",
                                        "reasoning",
                                        "thinkingLevelMap",
                                        "input",
                                        "contextWindowTokens",
                                        "maxTokens"
                                    ],
                                    "additionalProperties": false
                                }
                            }
                        },
                        "required": [
                            "models"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        }
    }
} as never,
});

/** 返回只读 Model Library；它不代表当前 Provider 的远程可用模型。 */
export default defineEventHandler((): ModelLibraryDto => modelLibrary());
