import {providerTemplateLibrary} from "nbook/server/models/provider-template-library";
import type {ProviderTemplateLibraryDto} from "nbook/shared/dto/app-settings.dto";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Config"
    ],
    "summary": "Read the NeuroBook provider template library",
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "templates": {
                                "default": [],
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "string",
                                            "minLength": 1,
                                            "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]*$"
                                        },
                                        "name": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "baseUrl": {
                                            "type": "string"
                                        },
                                        "defaultModelApi": {
                                            "nullable": true,
                                            "type": "string",
                                            "enum": [
                                                "openai-completions",
                                                "openai-responses",
                                                "anthropic-messages",
                                                "google-generative-ai",
                                                "bedrock-converse-stream"
                                            ]
                                        },
                                        "models": {
                                            "default": [],
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "name": {
                                                        "type": "string",
                                                        "minLength": 1
                                                    },
                                                    "id": {
                                                        "type": "string",
                                                        "minLength": 1
                                                    },
                                                    "group": {},
                                                    "enabled": {
                                                        "default": true,
                                                        "type": "boolean"
                                                    },
                                                    "api": {
                                                        "default": null,
                                                        "nullable": true,
                                                        "type": "string",
                                                        "minLength": 1
                                                    },
                                                    "reasoning": {
                                                        "default": null,
                                                        "nullable": true,
                                                        "type": "boolean"
                                                    },
                                                    "input": {
                                                        "default": null,
                                                        "nullable": true,
                                                        "minItems": 1,
                                                        "type": "array",
                                                        "items": {
                                                            "type": "string",
                                                            "enum": [
                                                                "text",
                                                                "image"
                                                            ]
                                                        }
                                                    },
                                                    "maxTokens": {
                                                        "default": null,
                                                        "nullable": true,
                                                        "type": "integer",
                                                        "minimum": 0,
                                                        "exclusiveMinimum": true,
                                                        "maximum": 9007199254740991
                                                    },
                                                    "cost": {
                                                        "default": null,
                                                        "nullable": true,
                                                        "type": "object",
                                                        "properties": {
                                                            "input": {
                                                                "type": "number",
                                                                "minimum": 0
                                                            },
                                                            "output": {
                                                                "type": "number",
                                                                "minimum": 0
                                                            },
                                                            "cacheRead": {
                                                                "type": "number",
                                                                "minimum": 0
                                                            },
                                                            "cacheWrite": {
                                                                "type": "number",
                                                                "minimum": 0
                                                            },
                                                            "tiers": {
                                                                "default": [],
                                                                "type": "array",
                                                                "items": {
                                                                    "type": "object",
                                                                    "properties": {
                                                                        "inputTokensAbove": {
                                                                            "type": "integer",
                                                                            "minimum": 0,
                                                                            "maximum": 9007199254740991
                                                                        },
                                                                        "input": {
                                                                            "type": "number",
                                                                            "minimum": 0
                                                                        },
                                                                        "output": {
                                                                            "type": "number",
                                                                            "minimum": 0
                                                                        },
                                                                        "cacheRead": {
                                                                            "type": "number",
                                                                            "minimum": 0
                                                                        },
                                                                        "cacheWrite": {
                                                                            "type": "number",
                                                                            "minimum": 0
                                                                        }
                                                                    },
                                                                    "required": [
                                                                        "inputTokensAbove",
                                                                        "input",
                                                                        "output",
                                                                        "cacheRead",
                                                                        "cacheWrite"
                                                                    ],
                                                                    "additionalProperties": false
                                                                }
                                                            }
                                                        },
                                                        "required": [
                                                            "input",
                                                            "output",
                                                            "cacheRead",
                                                            "cacheWrite",
                                                            "tiers"
                                                        ],
                                                        "additionalProperties": false
                                                    },
                                                    "compat": {
                                                        "default": null,
                                                        "nullable": true,
                                                        "type": "object",
                                                        "additionalProperties": {
                                                            "$ref": "#/definitions/__schema0"
                                                        }
                                                    },
                                                    "headers": {
                                                        "default": null,
                                                        "nullable": true,
                                                        "type": "object",
                                                        "additionalProperties": {
                                                            "nullable": true,
                                                            "type": "string"
                                                        }
                                                    },
                                                    "thinkingLevelMap": {
                                                        "default": null,
                                                        "nullable": true,
                                                        "type": "object",
                                                        "additionalProperties": {
                                                            "nullable": true,
                                                            "type": "string"
                                                        }
                                                    },
                                                    "contextWindowTokens": {
                                                        "default": null,
                                                        "nullable": true,
                                                        "type": "integer",
                                                        "minimum": 0,
                                                        "exclusiveMinimum": true,
                                                        "maximum": 9007199254740991
                                                    }
                                                },
                                                "required": [
                                                    "name",
                                                    "id",
                                                    "group",
                                                    "enabled",
                                                    "api",
                                                    "reasoning",
                                                    "input",
                                                    "maxTokens",
                                                    "cost",
                                                    "compat",
                                                    "headers",
                                                    "thinkingLevelMap",
                                                    "contextWindowTokens"
                                                ],
                                                "additionalProperties": false
                                            }
                                        }
                                    },
                                    "required": [
                                        "id",
                                        "name",
                                        "baseUrl",
                                        "defaultModelApi",
                                        "models"
                                    ],
                                    "additionalProperties": false
                                }
                            }
                        },
                        "required": [
                            "templates"
                        ],
                        "additionalProperties": false,
                        "definitions": {
                            "__schema0": {
                                "anyOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "number"
                                    },
                                    {
                                        "type": "boolean"
                                    },
                                    {
                                        "type": "string",
                                        "nullable": true,
                                        "enum": [
                                            null
                                        ]
                                    },
                                    {
                                        "type": "array",
                                        "items": {
                                            "$ref": "#/definitions/__schema0"
                                        }
                                    },
                                    {
                                        "type": "object",
                                        "additionalProperties": {
                                            "$ref": "#/definitions/__schema0"
                                        }
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        }
    }
} as never,
});

/** 返回只读 Provider Template Library。 */
export default defineEventHandler((): ProviderTemplateLibraryDto => providerTemplateLibrary());
