import {createError, isError} from "h3";
import {DiscoverProviderModelsRequestDtoSchema, type DiscoverProviderModelsRequestDto} from "nbook/shared/dto/app-settings.dto";
import {loadGlobalEffectiveConfigSync} from "nbook/server/config/config-service";
import {discoverProviderModels} from "nbook/server/utils/model-settings";
import {resolveProviderCredential} from "nbook/server/models/provider-credential";
import {providerDiscoveryErrorCode} from "nbook/server/models/discovery";
import {validateBody} from "nbook/server/utils/novel-chapter";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Config"
    ],
    "summary": "Discover available models from a provider",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "provider": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string",
                                    "minLength": 1,
                                    "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]*$"
                                },
                                "name": {
                                    "type": "string",
                                    "minLength": 1
                                },
                                "modelApi": {
                                    "type": "string",
                                    "enum": [
                                        "openai-completions",
                                        "openai-responses",
                                        "anthropic-messages",
                                        "google-generative-ai",
                                        "bedrock-converse-stream"
                                    ]
                                },
                                "options": {
                                    "type": "object",
                                    "properties": {
                                        "apiKey": {
                                            "default": "",
                                            "type": "string"
                                        },
                                        "baseURL": {
                                            "default": "",
                                            "type": "string"
                                        },
                                        "proxy": {
                                            "default": "",
                                            "type": "string"
                                        },
                                        "timeoutMs": {
                                            "default": null,
                                            "nullable": true,
                                            "type": "integer",
                                            "minimum": 0,
                                            "exclusiveMinimum": true,
                                            "maximum": 9007199254740991
                                        },
                                        "requestOptions": {
                                            "default": {},
                                            "type": "object",
                                            "properties": {
                                                "temperature": {
                                                    "type": "number",
                                                    "minimum": 0
                                                },
                                                "headers": {
                                                    "type": "object",
                                                    "additionalProperties": {
                                                        "nullable": true,
                                                        "type": "string"
                                                    }
                                                },
                                                "websocketConnectTimeoutMs": {
                                                    "type": "integer",
                                                    "minimum": 0,
                                                    "exclusiveMinimum": true,
                                                    "maximum": 9007199254740991
                                                },
                                                "maxRetries": {
                                                    "type": "integer",
                                                    "minimum": 0,
                                                    "maximum": 9007199254740991
                                                },
                                                "maxRetryDelayMs": {
                                                    "type": "integer",
                                                    "minimum": 0,
                                                    "maximum": 9007199254740991
                                                },
                                                "metadata": {
                                                    "type": "object",
                                                    "additionalProperties": {
                                                        "$ref": "#/definitions/__schema0"
                                                    }
                                                },
                                                "env": {
                                                    "type": "object",
                                                    "additionalProperties": {
                                                        "type": "string"
                                                    }
                                                },
                                                "transport": {
                                                    "type": "string",
                                                    "enum": [
                                                        "sse",
                                                        "websocket",
                                                        "websocket-cached",
                                                        "auto"
                                                    ]
                                                },
                                                "cacheRetention": {
                                                    "type": "string",
                                                    "enum": [
                                                        "none",
                                                        "short",
                                                        "long"
                                                    ]
                                                },
                                                "thinkingBudgets": {
                                                    "type": "object",
                                                    "properties": {
                                                        "minimal": {
                                                            "type": "integer",
                                                            "minimum": 0,
                                                            "exclusiveMinimum": true,
                                                            "maximum": 9007199254740991
                                                        },
                                                        "low": {
                                                            "type": "integer",
                                                            "minimum": 0,
                                                            "exclusiveMinimum": true,
                                                            "maximum": 9007199254740991
                                                        },
                                                        "medium": {
                                                            "type": "integer",
                                                            "minimum": 0,
                                                            "exclusiveMinimum": true,
                                                            "maximum": 9007199254740991
                                                        },
                                                        "high": {
                                                            "type": "integer",
                                                            "minimum": 0,
                                                            "exclusiveMinimum": true,
                                                            "maximum": 9007199254740991
                                                        }
                                                    },
                                                    "additionalProperties": false
                                                }
                                            },
                                            "additionalProperties": false
                                        }
                                    },
                                    "required": [
                                        "apiKey",
                                        "baseURL",
                                        "proxy",
                                        "timeoutMs",
                                        "requestOptions"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "required": [
                                "id",
                                "name",
                                "modelApi",
                                "options"
                            ],
                            "additionalProperties": false
                        },
                        "credentialSource": {
                            "type": "string",
                            "enum": [
                                "provided",
                                "saved",
                                "cleared"
                            ]
                        }
                    },
                    "required": [
                        "provider",
                        "credentialSource"
                    ],
                    "additionalProperties": false,
                    "definitions": {
                        "__schema0": {
                            "anyOf": [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "number"
                                },
                                {
                                    "type": "boolean"
                                },
                                {
                                    "type": "string",
                                    "nullable": true,
                                    "enum": [
                                        null
                                    ]
                                },
                                {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/__schema0"
                                    }
                                },
                                {
                                    "type": "object",
                                    "additionalProperties": {
                                        "$ref": "#/definitions/__schema0"
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "models": {
                                "default": [],
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "name": {
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "group": {},
                                        "api": {
                                            "default": null,
                                            "nullable": true,
                                            "type": "string",
                                            "minLength": 1
                                        },
                                        "reasoning": {
                                            "default": null,
                                            "nullable": true,
                                            "type": "boolean"
                                        },
                                        "input": {
                                            "default": null,
                                            "nullable": true,
                                            "minItems": 1,
                                            "type": "array",
                                            "items": {
                                                "type": "string",
                                                "enum": [
                                                    "text",
                                                    "image"
                                                ]
                                            }
                                        },
                                        "contextWindowTokens": {
                                            "default": null,
                                            "nullable": true,
                                            "type": "integer",
                                            "minimum": 0,
                                            "exclusiveMinimum": true,
                                            "maximum": 9007199254740991
                                        },
                                        "maxTokens": {
                                            "default": null,
                                            "nullable": true,
                                            "type": "integer",
                                            "minimum": 0,
                                            "exclusiveMinimum": true,
                                            "maximum": 9007199254740991
                                        },
                                        "cost": {
                                            "default": null,
                                            "nullable": true,
                                            "type": "object",
                                            "properties": {
                                                "input": {
                                                    "type": "number",
                                                    "minimum": 0
                                                },
                                                "output": {
                                                    "type": "number",
                                                    "minimum": 0
                                                },
                                                "cacheRead": {
                                                    "type": "number",
                                                    "minimum": 0
                                                },
                                                "cacheWrite": {
                                                    "type": "number",
                                                    "minimum": 0
                                                },
                                                "tiers": {
                                                    "default": [],
                                                    "type": "array",
                                                    "items": {
                                                        "type": "object",
                                                        "properties": {
                                                            "inputTokensAbove": {
                                                                "type": "integer",
                                                                "minimum": 0,
                                                                "maximum": 9007199254740991
                                                            },
                                                            "input": {
                                                                "type": "number",
                                                                "minimum": 0
                                                            },
                                                            "output": {
                                                                "type": "number",
                                                                "minimum": 0
                                                            },
                                                            "cacheRead": {
                                                                "type": "number",
                                                                "minimum": 0
                                                            },
                                                            "cacheWrite": {
                                                                "type": "number",
                                                                "minimum": 0
                                                            }
                                                        },
                                                        "required": [
                                                            "inputTokensAbove",
                                                            "input",
                                                            "output",
                                                            "cacheRead",
                                                            "cacheWrite"
                                                        ],
                                                        "additionalProperties": false
                                                    }
                                                }
                                            },
                                            "required": [
                                                "input",
                                                "output",
                                                "cacheRead",
                                                "cacheWrite",
                                                "tiers"
                                            ],
                                            "additionalProperties": false
                                        },
                                        "compat": {
                                            "default": null,
                                            "nullable": true,
                                            "type": "object",
                                            "additionalProperties": {
                                                "$ref": "#/definitions/__schema0"
                                            }
                                        },
                                        "headers": {
                                            "default": null,
                                            "nullable": true,
                                            "type": "object",
                                            "additionalProperties": {
                                                "nullable": true,
                                                "type": "string"
                                            }
                                        },
                                        "thinkingLevelMap": {
                                            "default": null,
                                            "nullable": true,
                                            "type": "object",
                                            "additionalProperties": {
                                                "nullable": true,
                                                "type": "string"
                                            }
                                        }
                                    },
                                    "required": [
                                        "id",
                                        "name",
                                        "group",
                                        "api",
                                        "reasoning",
                                        "input",
                                        "contextWindowTokens",
                                        "maxTokens",
                                        "cost",
                                        "compat",
                                        "headers",
                                        "thinkingLevelMap"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "message": {
                                "type": "string",
                                "minLength": 1
                            },
                            "diagnostics": {
                                "type": "object",
                                "properties": {
                                    "fetchedCount": {
                                        "type": "integer",
                                        "minimum": 0,
                                        "maximum": 9007199254740991
                                    },
                                    "returnedCount": {
                                        "type": "integer",
                                        "minimum": 0,
                                        "maximum": 9007199254740991
                                    },
                                    "skippedCount": {
                                        "type": "integer",
                                        "minimum": 0,
                                        "maximum": 9007199254740991
                                    },
                                    "duplicateCount": {
                                        "type": "integer",
                                        "minimum": 0,
                                        "maximum": 9007199254740991
                                    },
                                    "pageCount": {
                                        "type": "integer",
                                        "minimum": 0,
                                        "maximum": 9007199254740991
                                    },
                                    "truncated": {
                                        "type": "boolean"
                                    },
                                    "partial": {
                                        "type": "boolean"
                                    }
                                },
                                "required": [
                                    "fetchedCount",
                                    "returnedCount",
                                    "skippedCount",
                                    "duplicateCount",
                                    "pageCount",
                                    "truncated",
                                    "partial"
                                ],
                                "additionalProperties": false
                            }
                        },
                        "required": [
                            "models",
                            "message",
                            "diagnostics"
                        ],
                        "additionalProperties": false,
                        "definitions": {
                            "__schema0": {
                                "anyOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "number"
                                    },
                                    {
                                        "type": "boolean"
                                    },
                                    {
                                        "type": "string",
                                        "nullable": true,
                                        "enum": [
                                            null
                                        ]
                                    },
                                    {
                                        "type": "array",
                                        "items": {
                                            "$ref": "#/definitions/__schema0"
                                        }
                                    },
                                    {
                                        "type": "object",
                                        "additionalProperties": {
                                            "$ref": "#/definitions/__schema0"
                                        }
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});







/**
 * 远程模型发现。凭据来源必须由调用方明确选择。
 */
export default defineEventHandler(async (event) => {
    const body = await validateBody<DiscoverProviderModelsRequestDto>(event, DiscoverProviderModelsRequestDtoSchema);
    try {
        return await discoverProviderModels(resolveProviderCredential(body.provider, body.credentialSource, loadGlobalEffectiveConfigSync()));
    } catch (error) {
        if (isError(error) && error.statusCode === 400) throw error;
        const code = providerDiscoveryErrorCode(error);
        throw createError({
            statusCode: resolveDiscoveryStatusCode(error),
            message: code && error instanceof Error ? error.message : "Provider 模型发现失败",
            ...(code ? {data: {code}} : {}),
        });
    }
});

/**
 * 将远程发现失败映射成稳定 HTTP 状态。
 */
function resolveDiscoveryStatusCode(error: unknown): number {
    switch (providerDiscoveryErrorCode(error)) {
        case "missing-base-url":
        case "invalid-base-url":
        case "unsupported-discovery":
            return 400;
        case "unauthorized":
            return 401;
        case "forbidden":
            return 403;
        case "rate-limited":
            return 429;
        case "timeout":
            return 504;
        default:
            return 502;
    }
}
