import {CheckProviderRequestDtoSchema, type CheckProviderRequestDto} from "nbook/shared/dto/app-settings.dto";
import {loadGlobalEffectiveConfigSync} from "nbook/server/config/config-service";
import {checkProviderConnection} from "nbook/server/utils/model-settings";
import {resolveProviderCredential} from "nbook/server/models/provider-credential";
import {validateBody} from "nbook/server/utils/novel-chapter";
import {useAgentHarness} from "nbook/server/agent/http";

// AUTO-GENERATED by generate-openapi-meta — DO NOT EDIT
defineRouteMeta({
    openAPI: {
    "tags": [
        "Config"
    ],
    "summary": "Check connectivity of a model provider",
    "requestBody": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "provider": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string",
                                    "minLength": 1,
                                    "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]*$"
                                },
                                "name": {
                                    "type": "string",
                                    "minLength": 1
                                },
                                "modelApi": {
                                    "type": "string",
                                    "enum": [
                                        "openai-completions",
                                        "openai-responses",
                                        "anthropic-messages",
                                        "google-generative-ai",
                                        "bedrock-converse-stream"
                                    ]
                                },
                                "options": {
                                    "type": "object",
                                    "properties": {
                                        "apiKey": {
                                            "default": "",
                                            "type": "string"
                                        },
                                        "baseURL": {
                                            "default": "",
                                            "type": "string"
                                        },
                                        "proxy": {
                                            "default": "",
                                            "type": "string"
                                        },
                                        "timeoutMs": {
                                            "default": null,
                                            "nullable": true,
                                            "type": "integer",
                                            "minimum": 0,
                                            "exclusiveMinimum": true,
                                            "maximum": 9007199254740991
                                        },
                                        "requestOptions": {
                                            "default": {},
                                            "type": "object",
                                            "properties": {
                                                "temperature": {
                                                    "type": "number",
                                                    "minimum": 0
                                                },
                                                "headers": {
                                                    "type": "object",
                                                    "additionalProperties": {
                                                        "nullable": true,
                                                        "type": "string"
                                                    }
                                                },
                                                "websocketConnectTimeoutMs": {
                                                    "type": "integer",
                                                    "minimum": 0,
                                                    "exclusiveMinimum": true,
                                                    "maximum": 9007199254740991
                                                },
                                                "maxRetries": {
                                                    "type": "integer",
                                                    "minimum": 0,
                                                    "maximum": 9007199254740991
                                                },
                                                "maxRetryDelayMs": {
                                                    "type": "integer",
                                                    "minimum": 0,
                                                    "maximum": 9007199254740991
                                                },
                                                "metadata": {
                                                    "type": "object",
                                                    "additionalProperties": {
                                                        "$ref": "#/definitions/__schema0"
                                                    }
                                                },
                                                "env": {
                                                    "type": "object",
                                                    "additionalProperties": {
                                                        "type": "string"
                                                    }
                                                },
                                                "transport": {
                                                    "type": "string",
                                                    "enum": [
                                                        "sse",
                                                        "websocket",
                                                        "websocket-cached",
                                                        "auto"
                                                    ]
                                                },
                                                "cacheRetention": {
                                                    "type": "string",
                                                    "enum": [
                                                        "none",
                                                        "short",
                                                        "long"
                                                    ]
                                                },
                                                "thinkingBudgets": {
                                                    "type": "object",
                                                    "properties": {
                                                        "minimal": {
                                                            "type": "integer",
                                                            "minimum": 0,
                                                            "exclusiveMinimum": true,
                                                            "maximum": 9007199254740991
                                                        },
                                                        "low": {
                                                            "type": "integer",
                                                            "minimum": 0,
                                                            "exclusiveMinimum": true,
                                                            "maximum": 9007199254740991
                                                        },
                                                        "medium": {
                                                            "type": "integer",
                                                            "minimum": 0,
                                                            "exclusiveMinimum": true,
                                                            "maximum": 9007199254740991
                                                        },
                                                        "high": {
                                                            "type": "integer",
                                                            "minimum": 0,
                                                            "exclusiveMinimum": true,
                                                            "maximum": 9007199254740991
                                                        }
                                                    },
                                                    "additionalProperties": false
                                                }
                                            },
                                            "additionalProperties": false
                                        }
                                    },
                                    "required": [
                                        "apiKey",
                                        "baseURL",
                                        "proxy",
                                        "timeoutMs",
                                        "requestOptions"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "required": [
                                "id",
                                "name",
                                "modelApi",
                                "options"
                            ],
                            "additionalProperties": false
                        },
                        "models": {
                            "default": [],
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "minLength": 1
                                    },
                                    "id": {
                                        "type": "string",
                                        "minLength": 1
                                    },
                                    "group": {},
                                    "api": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "string",
                                        "minLength": 1
                                    },
                                    "reasoning": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "boolean"
                                    },
                                    "input": {
                                        "default": null,
                                        "nullable": true,
                                        "minItems": 1,
                                        "type": "array",
                                        "items": {
                                            "type": "string",
                                            "enum": [
                                                "text",
                                                "image"
                                            ]
                                        }
                                    },
                                    "maxTokens": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "integer",
                                        "minimum": 0,
                                        "exclusiveMinimum": true,
                                        "maximum": 9007199254740991
                                    },
                                    "cost": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "object",
                                        "properties": {
                                            "input": {
                                                "type": "number",
                                                "minimum": 0
                                            },
                                            "output": {
                                                "type": "number",
                                                "minimum": 0
                                            },
                                            "cacheRead": {
                                                "type": "number",
                                                "minimum": 0
                                            },
                                            "cacheWrite": {
                                                "type": "number",
                                                "minimum": 0
                                            },
                                            "tiers": {
                                                "default": [],
                                                "type": "array",
                                                "items": {
                                                    "type": "object",
                                                    "properties": {
                                                        "inputTokensAbove": {
                                                            "type": "integer",
                                                            "minimum": 0,
                                                            "maximum": 9007199254740991
                                                        },
                                                        "input": {
                                                            "type": "number",
                                                            "minimum": 0
                                                        },
                                                        "output": {
                                                            "type": "number",
                                                            "minimum": 0
                                                        },
                                                        "cacheRead": {
                                                            "type": "number",
                                                            "minimum": 0
                                                        },
                                                        "cacheWrite": {
                                                            "type": "number",
                                                            "minimum": 0
                                                        }
                                                    },
                                                    "required": [
                                                        "inputTokensAbove",
                                                        "input",
                                                        "output",
                                                        "cacheRead",
                                                        "cacheWrite"
                                                    ],
                                                    "additionalProperties": false
                                                }
                                            }
                                        },
                                        "required": [
                                            "input",
                                            "output",
                                            "cacheRead",
                                            "cacheWrite",
                                            "tiers"
                                        ],
                                        "additionalProperties": false
                                    },
                                    "compat": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "object",
                                        "additionalProperties": {
                                            "$ref": "#/definitions/__schema1"
                                        }
                                    },
                                    "headers": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "object",
                                        "additionalProperties": {
                                            "nullable": true,
                                            "type": "string"
                                        }
                                    },
                                    "thinkingLevelMap": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "object",
                                        "additionalProperties": {
                                            "nullable": true,
                                            "type": "string"
                                        }
                                    },
                                    "contextWindowTokens": {
                                        "default": null,
                                        "nullable": true,
                                        "type": "integer",
                                        "minimum": 0,
                                        "exclusiveMinimum": true,
                                        "maximum": 9007199254740991
                                    }
                                },
                                "required": [
                                    "name",
                                    "id",
                                    "group",
                                    "api",
                                    "reasoning",
                                    "input",
                                    "maxTokens",
                                    "cost",
                                    "compat",
                                    "headers",
                                    "thinkingLevelMap",
                                    "contextWindowTokens"
                                ],
                                "additionalProperties": false
                            }
                        },
                        "credentialSource": {
                            "type": "string",
                            "enum": [
                                "provided",
                                "saved",
                                "cleared"
                            ]
                        },
                        "useSavedModels": {
                            "default": true,
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "provider",
                        "models",
                        "credentialSource",
                        "useSavedModels"
                    ],
                    "additionalProperties": false,
                    "definitions": {
                        "__schema0": {
                            "anyOf": [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "number"
                                },
                                {
                                    "type": "boolean"
                                },
                                {
                                    "type": "string",
                                    "nullable": true,
                                    "enum": [
                                        null
                                    ]
                                },
                                {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/__schema0"
                                    }
                                },
                                {
                                    "type": "object",
                                    "additionalProperties": {
                                        "$ref": "#/definitions/__schema0"
                                    }
                                }
                            ]
                        },
                        "__schema1": {
                            "anyOf": [
                                {
                                    "type": "string"
                                },
                                {
                                    "type": "number"
                                },
                                {
                                    "type": "boolean"
                                },
                                {
                                    "type": "string",
                                    "nullable": true,
                                    "enum": [
                                        null
                                    ]
                                },
                                {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/__schema1"
                                    }
                                },
                                {
                                    "type": "object",
                                    "additionalProperties": {
                                        "$ref": "#/definitions/__schema1"
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "responses": {
        "200": {
            "description": "OK",
            "content": {
                "application/json": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "success": {
                                "type": "boolean"
                            },
                            "latencyMs": {
                                "nullable": true,
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 9007199254740991
                            },
                            "message": {
                                "type": "string",
                                "minLength": 1
                            }
                        },
                        "required": [
                            "success",
                            "latencyMs",
                            "message"
                        ],
                        "additionalProperties": false
                    }
                }
            }
        },
        "400": {
            "description": "Bad Request — validation failed"
        }
    }
} as never,
});





/**
 * Provider 连通性测试。凭据来源必须由调用方明确选择。
 */
export default defineEventHandler(async (event) => {
    const body = await validateBody<CheckProviderRequestDto>(event, CheckProviderRequestDtoSchema);
    const config = loadGlobalEffectiveConfigSync();
    const provider = resolveProviderCredential(body.provider, body.credentialSource, config);
    const savedProvider = config.models.providers[body.provider.id];
    const modelDrafts = body.models.length > 0
        ? body.models
        : body.useSavedModels
            ? Object.values(savedProvider?.models ?? {})
                .filter((model) => model.enabled)
                .map((model) => ({
                    name: model.name,
                    id: model.id,
                    group: model.group,
                    api: model.api,
                    reasoning: model.reasoning,
                    input: model.input,
                    maxTokens: model.maxTokens,
                    cost: model.cost,
                    compat: model.compat,
                    headers: model.headers,
                    thinkingLevelMap: model.thinkingLevelMap,
                    contextWindowTokens: model.contextWindowTokens,
                }))
            : [];
    return checkProviderConnection(provider, modelDrafts, {
        trace: useAgentHarness().traceBinding(config, {kind: "health-check", mode: "provider-check"}),
    });
});
