import type {PlotPreviewDataset} from "nbook/app/components/novel-ide/plot/plot-preview.types";

/**
 * 剧情测试页 mock 数据。
 * 数据故意覆盖主线、支线、未挂章 Scene 和多种 Scene 承载关系。
 */
export const plotPreviewDataset: PlotPreviewDataset = {
    story: {
        id: "story-orphan-flame",
        title: "灰烬孤港",
        summary: "一名被当作货物买下的少女，在孤港与黑塔势力的拉扯中完成身份逆袭。",
    },
    phases: [
        {
            id: "phase-arrival",
            title: "第一幕 抵港与入笼",
            summary: "主角初入孤港，建立被压迫处境、价格悬念与交易规则。",
        },
        {
            id: "phase-unlock",
            title: "第二幕 钥匙与反咬",
            summary: "旧钥匙、债契与塔楼秘库交织，主线开始获得主动权。",
        },
        {
            id: "phase-burning",
            title: "第三幕 焚港与改名",
            summary: "多线开始并行回收，人物关系、身份和控制权在同一阶段爆裂。",
        },
    ],
    threads: [
        {
            id: "thread-main",
            phaseId: "phase-arrival",
            title: "主线：买下奴隶少女",
            summary: "围绕少女被买下、定价、试探和逆袭展开的核心因果线。",
            status: "active",
            isMainThread: true,
            tags: ["逆袭", "交易", "控制权"],
            writingTip: "主线场景要始终保留价格压力与身份压迫感，不要太早让主角完全松弛。",
            tone: "amber",
            refs: [
                {id: "ref-thread-main-1", relation: "involves", target: "lorebook/character/slave-girl/", visibility: "author", note: null},
                {id: "ref-thread-main-2", relation: "depends_on", target: "lorebook/item/debt-contract/", visibility: "author", note: "债契决定主线控制权的上限。"},
            ],
        },
        {
            id: "thread-key",
            phaseId: "phase-unlock",
            title: "支线：旧钥匙的真正用途",
            summary: "旧钥匙从不起眼物件逐渐升级为塔楼秘库入口的关键线索。",
            status: "active",
            isMainThread: false,
            tags: ["悬念", "伏笔", "秘库"],
            writingTip: "钥匙线不要一次解释完，尽量让每次出现都只推进半步理解。",
            tone: "sky",
            refs: [
                {id: "ref-thread-key-1", relation: "foreshadows", target: "scene://scene-vault-open", visibility: "author", note: "钥匙首次出现时正文不解释。"},
            ],
        },
        {
            id: "thread-emotion",
            phaseId: "phase-burning",
            title: "支线：买主与少女的情感反咬",
            summary: "从互相利用到互相试探，再到谁先暴露软肋的情感攻防。",
            status: "draft",
            isMainThread: false,
            tags: ["情感", "拉扯", "背刺"],
            writingTip: "情感推进不能脱离利益关系，甜和狠必须同时出现。",
            tone: "rose",
            refs: [
                {id: "ref-thread-emotion-1", relation: "involves", target: "lorebook/character/buyer/", visibility: "reader", note: null},
                {id: "ref-thread-emotion-2", relation: "involves", target: "lorebook/character/slave-girl/", visibility: "reader", note: null},
            ],
        },
        {
            id: "thread-harbor",
            phaseId: null,
            title: "未分组：孤港势力盘",
            summary: "用于整理港口帮派、黑塔使团和码头商会之间的权力结构。",
            status: "paused",
            isMainThread: false,
            tags: ["世界", "势力", "检索"],
            writingTip: null,
            tone: "emerald",
            refs: [
                {id: "ref-thread-harbor-1", relation: "mentions", target: "lorebook/location/ash-harbor/", visibility: "reader", note: null},
            ],
        },
    ],
    scenes: [
        {
            id: "scene-auction",
            threadId: "thread-main",
            chapterPath: "chapter-01",
            title: "拍卖台抬价",
            summary: "少女被推上台，买主以异常高价压住竞争者，同时暴露自身目的。",
            purpose: "建立交易爽点、压迫感与主线双方第一次互相观察。",
            status: "written",
            threadSortOrder: 0,
            chapterSortOrder: 0,
            writingTip: "要让现场像金融对赌，不是单纯的人口买卖陈列。",
            refs: [
                {id: "ref-scene-auction-1", relation: "setup_for", target: "scene://scene-ledger", visibility: "author", note: "高价会成为后续被反咬的理由。"},
            ],
        },
        {
            id: "scene-cage",
            threadId: "thread-main",
            chapterPath: "chapter-01",
            title: "笼中第一次对话",
            summary: "买主与少女在笼边试探底线，少女第一次试图反向定价自己。",
            purpose: "建立角色张力，让主角第一次显出不驯与计算能力。",
            status: "active",
            threadSortOrder: 1,
            chapterSortOrder: 1,
            writingTip: "对话节奏要像剥皮，一层层揭出谁在演戏。",
            refs: [
                {id: "ref-scene-cage-1", relation: "callbacks_to", target: "scene://scene-auction", visibility: "reader", note: null},
            ],
        },
        {
            id: "scene-key-first",
            threadId: "thread-key",
            chapterPath: "chapter-02",
            title: "旧钥匙第一次出现",
            summary: "少女从旧衣缝里摸出一把不起眼的钥匙，但没有解释来源。",
            purpose: "埋下钥匙线的第一层悬念。",
            status: "written",
            threadSortOrder: 0,
            chapterSortOrder: 0,
            writingTip: "不要聚焦钥匙本体，重点放在少女为什么不愿解释。",
            refs: [
                {id: "ref-scene-key-first-1", relation: "foreshadows", target: "scene://scene-vault-open", visibility: "author", note: null},
            ],
        },
        {
            id: "scene-ledger",
            threadId: "thread-main",
            chapterPath: "chapter-02",
            title: "账册房里的反咬",
            summary: "主角在账册房找到买主的亏空证据，第一次拥有议价资本。",
            purpose: "兑现第一轮逆袭爽点，让主角从被动转为半主动。",
            status: "active",
            threadSortOrder: 2,
            chapterSortOrder: 1,
            writingTip: "这里的爽点不是爆发，而是压低声音的反控。",
            refs: [
                {id: "ref-scene-ledger-1", relation: "payoff_of", target: "scene://scene-auction", visibility: "author", note: "高价带来的资金压力在这里回咬。"},
            ],
        },
        {
            id: "scene-vault-map",
            threadId: "thread-key",
            chapterPath: null,
            title: "秘库地图试拼",
            summary: "钥匙齿纹和港口旧地图被拼在一起，秘库入口位置初现轮廓。",
            purpose: "让钥匙线进入可规划状态，但暂时还没挂到正文。",
            status: "draft",
            threadSortOrder: 1,
            chapterSortOrder: null,
            writingTip: "这里更适合做 planning scene，信息要清晰但不必写成完整正文章节。",
            refs: [
                {id: "ref-scene-vault-map-1", relation: "depends_on", target: "lorebook/location/tower-vault/", visibility: "author", note: null},
            ],
        },
        {
            id: "scene-storm-confession",
            threadId: "thread-emotion",
            chapterPath: "chapter-04",
            title: "风暴夜里的半句坦白",
            summary: "买主说漏半句关于旧主人的往事，少女第一次判断他也在逃。",
            purpose: "推进情感线，但仍然保持双向利用关系。",
            status: "draft",
            threadSortOrder: 0,
            chapterSortOrder: 0,
            writingTip: "这一场不能写成纯感情戏，风暴和逃亡感要压住浪漫。",
            refs: [
                {id: "ref-scene-storm-1", relation: "contrasts_with", target: "scene://scene-cage", visibility: "reader", note: "同样是对话，但此时双方位置已经变化。"},
            ],
        },
        {
            id: "scene-vault-open",
            threadId: "thread-key",
            chapterPath: "chapter-05",
            title: "塔楼秘库开启",
            summary: "钥匙终于开门，但门后拿到的不是财富，而是一份能改写身份的旧记录。",
            purpose: "把钥匙悬念从物理目标反转成身份真相目标。",
            status: "draft",
            threadSortOrder: 2,
            chapterSortOrder: 0,
            writingTip: "这里必须先给‘拿到宝藏’的预期，再立刻打破。",
            refs: [
                {id: "ref-scene-vault-open-1", relation: "payoff_of", target: "scene://scene-key-first", visibility: "author", note: null},
            ],
        },
        {
            id: "scene-harbor-balance",
            threadId: "thread-harbor",
            chapterPath: null,
            title: "港口势力再洗牌",
            summary: "黑塔使团延迟进港，商会和码头护卫队出现新的权力空档。",
            purpose: "补足世界背景，暂时不进入正文章节。",
            status: "draft",
            threadSortOrder: 0,
            chapterSortOrder: null,
            writingTip: null,
            refs: [
                {id: "ref-scene-harbor-1", relation: "mentions", target: "lorebook/note/灰鸥商会/", visibility: "author", note: "该势力还没正式写进 lorebook。"},
            ],
        },
    ],
    chapters: [
        {
            id: "chapter-01",
            volumeTitle: "第一篇 入笼",
            numberLabel: "第01章",
            title: "买价",
            summary: "拍卖与笼边试探，完成主线首次建立。",
        },
        {
            id: "chapter-02",
            volumeTitle: "第一篇 入笼",
            numberLabel: "第02章",
            title: "钥匙",
            summary: "旧钥匙第一次出现，账册房完成第一轮反咬。",
        },
        {
            id: "chapter-03",
            volumeTitle: "第二篇 账册",
            numberLabel: "第03章",
            title: "空账",
            summary: "预留给主线后续压价与港口追索。",
        },
        {
            id: "chapter-04",
            volumeTitle: "第二篇 账册",
            numberLabel: "第04章",
            title: "风暴夜",
            summary: "情感线与逃亡线第一次并轨。",
        },
        {
            id: "chapter-05",
            volumeTitle: "第三篇 改名",
            numberLabel: "第05章",
            title: "秘库",
            summary: "钥匙线大回收，并把身份线推到台前。",
        },
    ],
};
